In [18]:
# Imports
import os
import sys
from IPython.display import display

from py_scripts.parser_registry import parse_files, list_parsers

# Backend selection ('music21' | 'partitura')
PARSING_BACKEND = 'partitura'

# Configuration
FILTER_ZERO_DURATION = True # filter out notes with duration 0 (grace notes)
ADJUST_FRACTIONAL_DURATION = True # rounds Duration, Local Onset, and Global Onset to 3 decimals
PARSE_ENHARMONIC = True     # add 'Pitch Enharmonic' column grounded in source notation
PLOTTING_BACKEND = 'bokeh'  # 'plt' | 'bokeh' | 'none'

SHOW_MEASURE_LINES = True   # draw vertical measure lines at measure starts
MEASURE_LINE_COLOR = 'black'  # color for the measure lines

HOVER_ENABLED = True        # enable hover tool (Bokeh only)
HOVER_FIELDS = ['measure', 'local_onset', 'global_onset', 'duration', 'pitch', 'pitch_enharmonic', 'midi', 'voice', 'xml_id'] # hover options as list

DISPLAY_PREVIEW = True      # show a preview of the parsed data as df
PREVIEW_ROWS = 20          # number of rows to show in the preview

CLEANUP_REMOTE = True       # if source is a URL, delete temp file after parsing
RETURN_PLOTS = False        # include plot objects in results under 'plot'
STRIP_TIES = True           # merge tied notes into single notes (music21 backend only)
ALIGN_ACCIDENT_SCHEMA = True # align accidentals on both parsing backends to the same schema (Pitch Enharmonic is parsed only in b/# format)

COLORIZE_VOICES = True      # color-code notes by voice/part in the piano roll
PALETTE = 'Category20'      # palette name ('Category10'/'tab10', 'Category20'/'tab20', 'Set3', or a list)
INCLUDE_XML_IDS = True      # if MEI, include xml:id per note as 'xml_id' column

# List of file sources (URLs or local paths)
FILE_SOURCES = [
    'https://analyse.hfm-weimar.de/database/02/PrJode_Jos0302_COM_1-5_MissaDapac_002_00006.xml',
    # 'https://raw.githubusercontent.com/humdrum-tools/bach-wtc-fugues/refs/heads/master/kern/wtc1f04.krn',
    #'https://raw.githubusercontent.com/humdrum-tools/bach-wtc/refs/heads/main/kern/wtc1f22.krn',
    # 'https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op31_No3_HenleUrtext/refs/heads/master/Beethoven_Op31_No3_3-HenleUrtext.mei'
    'https://raw.githubusercontent.com/piasteuck/winterreise-analysis/refs/heads/main/Schubert_Winterreise_Dataset_v2-0/01_RawData/score_musicxml/Schubert_D911-20.xml',
    # 'https://raw.githubusercontent.com/music-encoding/sample-encodings/main/MEI_5.0/Music/Complete_examples/Bach-JS_Ein_feste_Burg.mei',
    # 'https://raw.githubusercontent.com/music-encoding/sample-encodings/main/MEI_3.0/Music/Complete_examples/Mozart_Fuge_G_minor.mei'
    # 'https://raw.githubusercontent.com/humdrum-tools/bach-wtc/refs/heads/main/kern/wtc2f05.krn',
    # 'C:/Users/egorp/OneDrive/Desktop/weimar_ftp_backup/dokuwiki/database/05/CaSe_11_UNSP_UNSP_Danksagenw_005_00011.xml'  # If you prefer backslashes, make it a raw string: r'C:\Users\egorp\...'
]

# Plot sizing
PLOT_SIZE_X = 900  # width in pixels
PLOT_SIZE_Y = 600   # height in pixels

# Zoom tool dimensions: 'both' | 'width' (x-only) | 'height' (y-only)
# Bokeh only!
ZOOM_DRAG_DIM = 'both'
ZOOM_WHEEL_DIM = 'width'

# Parse and visualize
results, dfs_by_name, df_processed = parse_files(
    FILE_SOURCES,
    parsing_backend=PARSING_BACKEND,
    filter_zero_duration=FILTER_ZERO_DURATION,
    adjust_fractional_duration=ADJUST_FRACTIONAL_DURATION,
    parse_enharmonic=PARSE_ENHARMONIC,
    backend=PLOTTING_BACKEND,
    show_measure_lines=SHOW_MEASURE_LINES,
    measure_line_color=MEASURE_LINE_COLOR,
    show_hover=HOVER_ENABLED,
    hover_fields=HOVER_FIELDS,
    display_preview=DISPLAY_PREVIEW,
    preview_rows=PREVIEW_ROWS,
    cleanup_remote=CLEANUP_REMOTE,
    return_plots=RETURN_PLOTS,
    plot_width=PLOT_SIZE_X,
    plot_height=PLOT_SIZE_Y,
    zoom_drag_dim=ZOOM_DRAG_DIM,
    zoom_wheel_dim=ZOOM_WHEEL_DIM,
    strip_ties=STRIP_TIES,
    align_accident_schema=ALIGN_ACCIDENT_SCHEMA,
    colorize_voices=COLORIZE_VOICES,
    palette=PALETTE,
    include_xml_ids=INCLUDE_XML_IDS
)

# Show quick summary
print('Parsed DataFrames:')
for item in results:
    name = item['name']
    df = item['df']
    pos_dur = df.loc[df['Duration'] > 0, 'Duration'] if 'Duration' in df.columns else None
    min_dur_str = str(float(pos_dur.min())) if pos_dur is not None and len(pos_dur) > 0 else 'n/a'
    voice_count = df['Voice'].nunique() if 'Voice' in df.columns else 0
    voice_names = sorted(df['Voice'].unique().tolist()) if 'Voice' in df.columns else []
    print(f"- {name}: rows={len(df)}, unique_pitches={df['MIDI'].nunique()}, min_duration={min_dur_str}, voices={voice_count} ({voice_names})")

Parsing files:   0%|          | 0/2 [00:00<?, ?file/s]

Processing (partitura): PrJode_Jos0302_COM_1-5_MissaDapac_002_00006.xml -> 00_prjode_jos0302_com_1_5_missadapac_002_00006

    Measure  Local Onset  Global Onset  Duration Pitch Pitch Enharmonic  MIDI  \
0         1          3.0          -1.0       0.5    D4               D4    62
1         1          3.0          -1.0       1.0    F4               F4    65
2         1          3.0          -1.0       1.0    A4               A4    69
3         1          3.0          -1.0       1.0    D5               D5    74
4         1          3.5          -0.5       0.5    C4               C4    60
5         1          0.0           0.0       1.0    B3               B3    59
6         1          0.0           0.0       1.0    D4               D4    62
7         1          0.0           0.0       1.0    F4               F4    65
8         1          0.0           0.0       1.0    D5               D5    74
9         1          1.0           1.0       0.5    D4               D4    62
10        1          1.0           1.0       1.0    D5               D5    74
11        1          1.0           1.0       0.5    A3               A3    57
12        1          1.0           1.0       0.5    B3               B3    59
13        1          1.5           1.5       0.5    G3               G3    55
14        1          1.5           1.5       0.5    C4               C4    60
15        1          1.5           1.5       0.5    E4               E4    64
16        1          2.0           2.0       1.0    F3               F3    53
17        1          2.0           2.0       1.0    D4               D4    62
18        1          2.0           2.0       1.0    F4               F4    65
19        1          2.0           2.0       0.5    A4               A4    69

              Voice xml_id
0   Voice - Voice 1   <NA>
1   Voice - Voice 1   <NA>
2   Voice - Voice 1   <NA>
3   Voice - Voice 1   <NA>
4   Voice - Voice 1   <NA>
5   Voice - Voice 1   <NA>
6   Voice - Voice 1   <NA>
7   Voice - Voice 1   <NA>
8   Voice - Voice 1   <NA>
9   Voice - Voice 1   <NA>
10  Voice - Voice 1   <NA>
11  Voice - Voice 1   <NA>
12  Voice - Voice 1   <NA>
13  Voice - Voice 1   <NA>
14  Voice - Voice 1   <NA>
15  Voice - Voice 1   <NA>
16  Voice - Voice 1   <NA>
17  Voice - Voice 1   <NA>
18  Voice - Voice 1   <NA>
19  Voice - Voice 1   <NA>

Rows: 755, unique pitches: 24
Processing (partitura): Schubert_D911-20.xml -> 01_schubert_d911_20

c:\Users\sende\miniconda3\envs\camat_v2\Lib\site-packages\partitura\directions.py:514: UserWarning: error parsing "Mäßig" (UnexpectedCharacters)
  warnings.warn('error parsing "{}" ({})'.format(string, type(e).__name__))
c:\Users\sende\miniconda3\envs\camat_v2\Lib\site-packages\partitura\io\importmusicxml.py:1065: UserWarning: ignoring direction type: other-direction {'default-y': '14', 'print-object': 'no'}
  warnings.warn("ignoring direction type: {} {}".format(dt.tag, dt.attrib))
c:\Users\sende\miniconda3\envs\camat_v2\Lib\site-packages\partitura\io\importmusicxml.py:1065: UserWarning: ignoring direction type: other-direction {'default-y': '-53', 'print-object': 'no'}
  warnings.warn("ignoring direction type: {} {}".format(dt.tag, dt.attrib))

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,1.50,-0.50,0.25,A#3,G4,58,Piano - Voice 4,<NA>
1,1,1.50,-0.50,0.25,G4,Bb3,67,Piano - Voice 1,<NA>
2,1,1.75,-0.25,0.25,C4,A4,60,Piano - Voice 4,<NA>
3,1,1.75,-0.25,0.25,A4,C4,69,Piano - Voice 1,<NA>
4,1,0.00,0.00,0.50,G3,G4,55,Piano - Voice 4,<NA>
5,1,0.00,0.00,0.50,D4,Bb4,62,Piano - Voice 1,<NA>
6,1,0.00,0.00,0.50,G4,G3,67,Piano - Voice 1,<NA>
7,1,0.00,0.00,0.50,A#4,D4,70,Piano - Voice 1,<NA>
8,1,0.50,0.50,0.50,G3,G4,55,Piano - Voice 4,<NA>
9,1,0.50,0.50,0.50,D4,Bb4,62,Piano - Voice 1,<NA>
10,1,0.50,0.50,0.50,G4,G3,67,Piano - Voice 1,<NA>
11,1,0.50,0.50,0.50,A#4,D4,70,Piano - Voice 1,<NA>
12,1,1.00,1.00,0.50,G3,G4,55,Piano - Voice 4,<NA>
13,1,1.00,1.00,0.50,D4,Bb4,62,Piano - Voice 1,<NA>
14,1,1.00,1.00,0.50,G4,G3,67,Piano - Voice 1,<NA>
15,1,1.00,1.00,0.50,A#4,D4,70,Piano - Voice 1,<NA>
16,1,1.50,1.50,0.50,G3,G4,55,Piano - Voice 4,<NA>
17,1,1.50,1.50,0.50,D4,Bb4,62,Piano - Voice 1,<NA>
18,1,1.50,1.50,0.50,G4,G3,67,Piano - Voice 1,<NA>
19,1,1.50,1.50,0.50,A#4,D4,70,Piano - Voice 1,<NA>

Rows: 1131, unique pitches: 43
Parsed DataFrames:
- 00_prjode_jos0302_com_1_5_missadapac_002_00006: rows=755, unique_pitches=24, min_duration=0.5, voices=1 (['Voice - Voice 1'])
- 01_schubert_d911_20: rows=1131, unique_pitches=43, min_duration=0.125, voices=6 (['Piano - Voice 1', 'Piano - Voice 2', 'Piano - Voice 3', 'Piano - Voice 4', 'Piano - Voice 5', 'Voice - Voice 1'])

In [30]:
list(dfs_by_name)

['00_prjode_jos0302_com_1_5_missadapac_002_00006', '01_schubert_d911_20']

In [31]:
list(FILE_SOURCES)

['https://analyse.hfm-weimar.de/database/02/PrJode_Jos0302_COM_1-5_MissaDapac_002_00006.xml',
 'https://raw.githubusercontent.com/piasteuck/winterreise-analysis/refs/heads/main/Schubert_Winterreise_Dataset_v2-0/01_RawData/score_musicxml/Schubert_D911-20.xml']

In [32]:
from py_scripts import (
    vrv_set_options, vrv_load_from_url, vrv_render_all_pages, vrv_display_svg
)

url = FILE_SOURCES[1]

vrv_set_options(pageWidth=12000, pageHeight=1200, scale=40, breaks="none")
_ = vrv_load_from_url(url)  # auto detects 'mei' | 'musicxml' | 'humdrum'
for svg in vrv_render_all_pages():
    vrv_display_svg(svg)

In [33]:
df1 = results[0]['df']
df2 = results[1]['df']

display(df1)
display(df2)

     Measure  Local Onset  Global Onset  Duration Pitch Pitch Enharmonic  \
0          1          3.0          -1.0       0.5    D4               D4
1          1          3.0          -1.0       1.0    F4               F4
2          1          3.0          -1.0       1.0    A4               A4
3          1          3.0          -1.0       1.0    D5               D5
4          1          3.5          -0.5       0.5    C4               C4
..       ...          ...           ...       ...   ...              ...
230        4         37.5          45.5       0.5    G3               G3
231        4         38.0          46.0       1.0    F3               F3
232        4         38.0          46.0       1.0    A3               A3
233        4         38.0          46.0       1.0    D2               D2
234        4         38.0          46.0       1.0    D4               D4

     MIDI            Voice xml_id
0      55  Voice - Voice 1   <NA>
1      53  Voice - Voice 1   <NA>
2      55  Voice - Voice 1   <NA>
3      67  Voice - Voice 1   <NA>
4      57  Voice - Voice 1   <NA>
..    ...              ...    ...
750    66  Voice - Voice 1   <NA>
751    64  Voice - Voice 1   <NA>
752    43  Voice - Voice 1   <NA>
753    55  Voice - Voice 1   <NA>
754    67  Voice - Voice 1   <NA>

[755 rows x 9 columns]

      Measure  Local Onset  Global Onset  Duration Pitch Pitch Enharmonic  \
0           1         1.50         -0.50      0.25   A#3               G4
1           1         1.50         -0.50      0.25    G4              Bb3
2           1         1.75         -0.25      0.25    C4               A4
3           1         1.75         -0.25      0.25    A4               C4
4           1         0.00          0.00      0.50    G3               G4
...       ...          ...           ...       ...   ...              ...
1518       26       308.00        408.00      1.00    C4               C4
1519       26       308.00        408.00      1.00    A4               A4
1520       26       309.00        409.00      4.00    D4               D4
1521       26       309.00        409.00      4.00    G3               G3
1522       26       309.00        409.00      4.00    B4               B4

      MIDI            Voice xml_id
0       58  Piano - Voice 4   <NA>
1       67  Piano - Voice 1   <NA>
2       60  Piano - Voice 4   <NA>
3       69  Piano - Voice 1   <NA>
4       55  Piano - Voice 4   <NA>
...    ...              ...    ...
1126    67  Piano - Voice 1   <NA>
1127    31  Piano - Voice 4   <NA>
1128    58  Piano - Voice 1   <NA>
1129    62  Piano - Voice 1   <NA>
1130    67  Piano - Voice 1   <NA>

[1131 rows x 9 columns]

In [6]:
# Showcase: filtering/selecting from a notes DataFrame + piano-roll plot (refactored)

from py_scripts import display_filtered_piano_roll

# --- Configuration ---
SOURCE_DF = df2             # which dataframe to use (df1, df2, etc.)
MEASURE_RANGE = None        # (start, end) inclusive, or None
ONSET_RANGE = (5, 25)       # (start, end) exclusive at end [start, end), or None
VOICE_QUERY = ["P1 - Voice 1", "P2 - Voice 1"]  # regex string OR list of exact voice names, or None
PITCH_RANGE = None          # pitch range filter; accepts MIDI or names, e.g. (60, 72) or "g3-g5"

# Display options for the selection DataFrame
DISPLAY_SELECTION = True    # True = show selection, False = hide
DISPLAY_MODE = "head"       # 'head' (default), 'all', or 'none'
DISPLAY_MAX_ROWS = 20       # how many rows to show in 'head' mode

# Plotting options
PLOTTING_BACKEND = (PLOTTING_BACKEND.lower() if 'PLOTTING_BACKEND' in globals() else 'plt')
PLOT_WIDTH = (PLOT_SIZE_X if 'PLOT_SIZE_X' in globals() else None)
PLOT_HEIGHT = (PLOT_SIZE_Y if 'PLOT_SIZE_Y' in globals() else None)

# Optional: pass through `results` if you have it from earlier parsing steps
_results_arg = results if 'results' in globals() else None

selection = display_filtered_piano_roll(
    SOURCE_DF,
    measure_range=MEASURE_RANGE,
    onset_range=ONSET_RANGE,
    voice_query=VOICE_QUERY,
    pitch_range=PITCH_RANGE,
    results=_results_arg,
    plotting_backend=PLOTTING_BACKEND,
    plot_width=PLOT_WIDTH,
    plot_height=PLOT_HEIGHT,
    zoom_drag_dim=ZOOM_DRAG_DIM if 'ZOOM_DRAG_DIM' in globals() else None,
    zoom_wheel_dim=ZOOM_WHEEL_DIM if 'ZOOM_WHEEL_DIM' in globals() else None,
    show_measure_lines=True,
    display_selection=DISPLAY_SELECTION,
    display_mode=DISPLAY_MODE,
    display_max_rows=DISPLAY_MAX_ROWS,
)

Filtered by Global Onset [5, 25): 60 rows
Filtered by Voice list (2 voices): 47 rows

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
6,1,5.00,5.00,1.50,A4,A4,69,P1 - Voice 1,d1e427
7,1,6.50,6.50,0.50,D#5,Eb5,75,P1 - Voice 1,d1e442
8,1,7.00,7.00,0.50,D5,D5,74,P1 - Voice 1,d1e460
9,1,7.50,7.50,0.50,C5,C5,72,P1 - Voice 1,d1e476
10,1,8.00,8.00,0.50,A#4,Bb4,70,P1 - Voice 1,d1e515
11,1,8.00,8.00,2.00,G4,G4,67,P2 - Voice 1,d1e630
12,1,8.50,8.50,0.50,A4,A4,69,P1 - Voice 1,d1e533
13,1,9.00,9.00,0.50,A#4,Bb4,70,P1 - Voice 1,d1e549
14,1,9.50,9.50,0.50,C5,C5,72,P1 - Voice 1,d1e567
15,1,10.00,10.00,1.50,F4,F4,65,P2 - Voice 1,d1e644
16,1,10.00,10.00,0.50,D5,D5,74,P1 - Voice 1,d1e583
17,1,10.50,10.50,0.50,A4,A4,69,P1 - Voice 1,d1e599
18,1,11.00,11.00,1.00,D5,D5,74,P1 - Voice 1,d1e615
19,1,11.50,11.50,0.25,E4,E4,64,P2 - Voice 1,d1e659
20,1,11.75,11.75,0.25,D4,D4,62,P2 - Voice 1,d1e679
21,1,12.00,12.00,1.50,E5,E5,76,P1 - Voice 1,d1e713
22,1,12.00,12.00,0.50,C#4,C#4,61,P2 - Voice 1,d1e763
23,1,12.50,12.50,0.50,D4,D4,62,P2 - Voice 1,d1e783
24,1,13.00,13.00,1.50,E4,E4,64,P2 - Voice 1,d1e799
25,1,13.50,13.50,0.50,D5,D5,74,P1 - Voice 1,d1e730

In [7]:
# Showcase: filtering/selecting from a notes DataFrame + piano-roll plot (refactored)

from py_scripts import display_filtered_piano_roll

# --- Configuration ---
SOURCE_DF = df2             # which dataframe to use (df1, df2, etc.)
MEASURE_RANGE = (20, 35)         # (start, end) inclusive, or None
ONSET_RANGE = None       # (start, end) exclusive at end [start, end), or None
VOICE_QUERY = ["P1 - Voice 1"]  # regex string OR list of exact voice names, or None
PITCH_RANGE = None          # pitch range filter; accepts MIDI or names, e.g. (60, 72) or "g3-g5"

# Display options for the selection DataFrame
DISPLAY_SELECTION = True    # True = show selection, False = hide
DISPLAY_MODE = "head"       # 'head' (default), 'all', or 'none'
DISPLAY_MAX_ROWS = 20       # how many rows to show in 'head' mode

# Plotting options
PLOTTING_BACKEND = (PLOTTING_BACKEND.lower() if 'PLOTTING_BACKEND' in globals() else 'plt')
PLOT_WIDTH = (PLOT_SIZE_X if 'PLOT_SIZE_X' in globals() else None)
PLOT_HEIGHT = (PLOT_SIZE_Y if 'PLOT_SIZE_Y' in globals() else None)

# Optional: pass through `results` if you have it from earlier parsing steps
_results_arg = results if 'results' in globals() else None

selection2 = display_filtered_piano_roll(
    SOURCE_DF,
    measure_range=MEASURE_RANGE,
    onset_range=ONSET_RANGE,
    voice_query=VOICE_QUERY,
    pitch_range=PITCH_RANGE,
    results=_results_arg,
    plotting_backend=PLOTTING_BACKEND,
    plot_width=PLOT_WIDTH,
    plot_height=PLOT_HEIGHT,
    zoom_drag_dim=ZOOM_DRAG_DIM if 'ZOOM_DRAG_DIM' in globals() else None,
    zoom_wheel_dim=ZOOM_WHEEL_DIM if 'ZOOM_WHEEL_DIM' in globals() else None,
    show_measure_lines=True,
    display_selection=DISPLAY_SELECTION,
    display_mode=DISPLAY_MODE,
    display_max_rows=DISPLAY_MAX_ROWS,
)

Filtered by Measure [20, 35]: 380 rows
Filtered by Voice list (1 voices): 108 rows

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
1143,20,228.00,304.00,1.00,F#4,F#4,66,P1 - Voice 1,d1e20987
1148,20,229.00,305.00,1.00,G4,G4,67,P1 - Voice 1,d1e21005
1151,20,230.00,306.00,1.50,C5,C5,72,P1 - Voice 1,d1e21019
1155,20,231.50,307.50,0.25,B4,B4,71,P1 - Voice 1,d1e21039
1156,20,231.75,307.75,0.25,C5,C5,72,P1 - Voice 1,d1e21059
1160,20,232.00,308.00,0.50,D5,D5,74,P1 - Voice 1,d1e21274
1162,20,232.50,308.50,0.50,D#5,Eb5,75,P1 - Voice 1,d1e21290
1163,20,233.00,309.00,1.50,F5,F5,77,P1 - Voice 1,d1e21308
1174,20,234.50,310.50,0.50,D5,D5,74,P1 - Voice 1,d1e21323
1175,20,235.00,311.00,2.00,C5,C5,72,P1 - Voice 1,d1e21337
1183,20,237.00,313.00,2.00,A#4,Bb4,70,P1 - Voice 1,d1e21661
1188,20,239.00,315.00,0.50,A4,A4,69,P1 - Voice 1,d1e21677
1191,20,239.50,315.50,0.50,G4,G4,67,P1 - Voice 1,d1e21693
1195,20,240.00,316.00,1.00,G4,G4,67,P1 - Voice 1,d1e21897
1197,20,241.00,317.00,0.50,F#4,F#4,66,P1 - Voice 1,d1e21911
1199,20,241.50,317.50,0.50,E4,E4,64,P1 - Voice 1,d1e21931
1200,20,242.00,318.00,2.00,F#4,F#4,66,P1 - Voice 1,d1e21949
1209,21,246.00,326.00,2.00,D5,D5,74,P1 - Voice 1,d1e22163
1214,21,248.00,328.00,1.50,A#4,Bb4,70,P1 - Voice 1,d1e22304
1217,21,249.50,329.50,0.25,A4,A4,69,P1 - Voice 1,d1e22321

In [36]:
# 1. Extract xml_ids from the 'selection' variable created in the previous cell
# We add the '#' prefix which Verovio expects for plist references
from py_scripts import extract_selected_xml_ids

# Explicitly define the selection DataFrame variable
selection_df = selection2

# Push all the logic into the helper
selected_xml_ids = extract_selected_xml_ids(selection_df)

print(f"Passing {len(selected_xml_ids)} selected notes to annotation.")

# 2. Use it in your ANNOTS list
from py_scripts import (
    vrv_set_options, vrv_load_from_url, vrv_process_annotations
)
vrv_set_options(pageWidth=12000, pageHeight=1200, scale=40, breaks="none", removeIds=False, xmlIdSeed=0)
vrv_load_from_url(url)

ANNOTS = [
    # Plist annotation using the selection from the previous cell
    {
        "text": "Filtered Selection", 
        "type": "score", 
        "plist": selected_xml_ids, 
        "xml_id": "selection-annot"
    },
]

# Process all annotations
vrv_process_annotations(
    ANNOTS,
    highlight_color='#5427F5',
    shape_only=True,
    display=True
)

Passing 108 selected notes to annotation.

In [29]:
# Refactored pitch distribution using py_scripts.analysis_utils
from py_scripts import display_pitch_distribution

# Configuration for this cell (all lowercase options)
#
# PITCH_X_AXIS controls which pitch representation is used on the X axis:
#   - 'midi': use numeric MIDI values. If 'MIDI' column is missing, it is derived from names.
#   - 'pitch real' (synonyms: 'pitch', 'real'): use real pitch names corresponding to actual semitone values;
#       if only MIDI is present, names are derived from MIDI. Octave is included in the label.
#   - 'pitch enharmonic' (synonyms: 'pitch by name', 'pitch name', 'name', 'pitch_enharmonic', 'pitch-enharmonic'):
#       use written/enharmonic pitch names as notated (prefers 'Pitch Enharmonic' column),
#       preserving the spelled accidentals and octave, even if enharmonically different from real pitch.
PITCH_X_AXIS = 'pitch enharmonic'
#
# ORDER_X_AXIS_BY controls sort order of the X categories:
#   - 'midi' (synonyms: 'pitch real', 'pitch', 'real'):
#       sort by real MIDI number ascending (identical for all synonyms).
#   - 'pitch by octave real' (synonyms: 'pitch by octave', 'pitch octave', 'octave pitch', 'octave real'):
#       sort by REAL octave (computed from MIDI), then by pitch class within each octave.
#       This cares about actual pitch height. Example: B##3 resolves to its real octave (4); Cbb4 resolves to 3.
#   - 'pitch by octave enharmonic' (synonyms: 'octave enharmonic', 'octave name'):
#       sort by WRITTEN octave parsed from the name (ignoring semitone shifts of accidentals),
#       then by letter and accidental. Example: B##3 stays in octave 3; Cbb4 stays in octave 4.
#   - 'pitch by name' (synonyms: 'pitch enharmonic', 'enharmonic', 'enharmonic pitch', 'pitch_enharmonic'):
#       sort by letter (C..B) and accidental rank (bbb < bb < b < natural < # < ## < ###),
#       ignoring octave; ties are stabilized by the full label.
ORDER_X_AXIS_BY = 'midi'

# Plotting backend
PLOTTING_BACKEND = 'bokeh'        # 'plt' | 'bokeh' | 'none'

# Plot sizing for this cell (universal for both backends)
PLOT_SIZE_X = 1200
PLOT_SIZE_Y = 450

# Bokeh hover config
BOKEH_HOVER_VALUES = True

# Bar color for this plot
PITCH_BAR_COLOR = '#4682B4' # bar color(s) for pitch distribution plot(s) 

# Choose the DataFrame to visualize
source = (selection, selection2)  # e.g., df1, results[0]['df'], dfs_by_name['00_some_name'] or a selection from df

counts_df = display_pitch_distribution(
    source,
    source_labels=['selection1', 'selection2'],
    pitch_axis=PITCH_X_AXIS,
    order_axis_by=ORDER_X_AXIS_BY,
    backend=(PLOTTING_BACKEND.lower() if 'PLOTTING_BACKEND' in globals() else 'plt'),
    plot_width=PLOT_SIZE_X,
    plot_height=PLOT_SIZE_Y,
    show_hover=('BOKEH_HOVER_VALUES' in globals() and BOKEH_HOVER_VALUES),
    show_table=True,
    bar_color=PITCH_BAR_COLOR,
)

=== Pitch Distribution (selection1) ===

                  count
Pitch Enharmonic
C#4                   1
D4                    3
E4                    3
F4                    1
F#4                   3
G4                    5
A4                    7
Bb4                   8
C5                    6
C#5                   1
D5                    6
Eb5                   2
E5                    1

=== Pitch Distribution (selection2) ===

                  count
Pitch Enharmonic
E4                    2
F4                    2
F#4                   7
G4                   14
Ab4                   1
A4                   11
Bb4                  10
B4                    7
C5                   17
C#5                   1
D5                   22
Eb5                   7
E5                    2
F5                    3
G5                    2

In [10]:
# Duration distribution: count and visualize as bar plot (plt or bokeh)
# Uses global PLOTTING_BACKEND ('plt' or 'bokeh')

from py_scripts.analysis_utils import display_duration_distribution


# Configuration for this cell
DROP_ZERO_DURATIONS = True          # drop duration == 0
DURATION_ROUND_DECIMALS = 4         # round durations for cleaner categories; set None to disable
DURATION_BAR_COLOR = '#4682B4', '#adf542'     # bar color(s) for duration plot(s)

# Choose the DataFrame to visualize
source = (selection, selection2)   # e.g., df1, results[0]['df'], dfs_by_name['00_some_name'] or a selection from df

# Assign to variable to avoid double display (function displays table, return value displays again)
duration_counts = display_duration_distribution(
    source,
    source_labels=['selection1', 'selection2'],
    drop_zero=DROP_ZERO_DURATIONS,
    round_decimals=DURATION_ROUND_DECIMALS,
    backend=(PLOTTING_BACKEND if 'PLOTTING_BACKEND' in globals() else 'bokeh'),
    plot_width=1200,
    plot_height=350,
    bar_color=DURATION_BAR_COLOR,
)

=== Duration Distribution (selection1) ===

          count
Duration
0.25          4
0.50         30
1.00          2
1.50          5
2.00          5
2.50          1

=== Duration Distribution (selection2) ===

          count
Duration
0.25         28
0.50         37
1.00         15
1.50         16
2.00          9
3.00          2
4.00          1

In [12]:
# Pitch Class Distribution Analysis (Real + Enharmonic)
from py_scripts import display_pitch_class_distributions

# Configuration (inherits from previous cell if available)
PLOTTING_BACKEND = 'bokeh'
w_pc = PLOT_SIZE_X if 'PLOT_SIZE_X' in globals() else 1200
h_pc = PLOT_SIZE_Y if 'PLOT_SIZE_Y' in globals() else 450
PC_BAR_COLOR = '#4682B4', '#adf542' # bar color(s) for pitch-class plots

# Choose the DataFrame to analyze (e.g. df1, results[0]['df'], dfs_by_name['00_...'], or a filtered selection)
source = (selection, selection2)   # uses 'selection' from the previous context

# Build and display pitch-class distributions for real and enharmonic spellings
pc_results = display_pitch_class_distributions(
    source,
    source_labels=['selection1', 'selection2'],
    backend=PLOTTING_BACKEND,
    plot_width=w_pc,
    plot_height=h_pc,
    show_hover=True,
    show_table=True,
    bar_color=PC_BAR_COLOR,
)

=== Pitch Class Distribution (Real) — selection1 ===

Pitch Class (Real)  C  C#  D  D#  E  F  F#  G  A  A#
count               6   2  9   2  4  1   3  5  7   8

=== Pitch Class Distribution (Real) — selection2 ===

Pitch Class (Real)   C  C#   D  D#  E  F  F#   G  G#   A  A#  B
count               17   1  22   7  4  5   7  16   1  11  10  7

=== Pitch Class Distribution (Enharmonic / Written) — selection1 ===

Pitch Class (Enharmonic)  C  C#  D  Eb  E  F  F#  G  A  Bb
count                     6   2  9   2  4  1   3  5  7   8

=== Pitch Class Distribution (Enharmonic / Written) — selection2 ===

Pitch Class (Enharmonic)   C  C#   D  Eb  E  F  F#   G  Ab   A  Bb  B
count                     17   1  22   7  4  5   7  16   1  11  10  7

to do: intervall plot, combined plots