In [1]:
# Imports
import os
import sys
from IPython.display import display
from py_scripts.music_utils import parse_files

# Configuration
FILTER_ZERO_DURATION = True
ADJUST_FRACTIONAL_DURATION = True
PLOTTING_BACKEND = 'bokeh'  # 'plt' | 'bokeh' | 'none'
SHOW_MEASURE_LINES = True   # draw red vertical lines at measure starts
DISPLAY_PREVIEW = True
PREVIEW_ROWS = 20
CLEANUP_REMOTE = True       # if source is a URL, delete temp file after parsing
RETURN_PLOTS = False        # include plot objects in results under 'plot'

# List of file sources (URLs or local paths)
FILE_SOURCES = [
    'https://analyse.hfm-weimar.de/database/02/PrJode_Jos0302_COM_1-5_MissaDapac_002_00006.xml',
    'https://raw.githubusercontent.com/humdrum-tools/bach-wtc-fugues/refs/heads/master/kern/wtc1f04.krn'
]

# Parse and visualize
results, dfs_by_name, df_processed = parse_files(
    FILE_SOURCES,
    filter_zero_duration=FILTER_ZERO_DURATION,
    adjust_fractional_duration=ADJUST_FRACTIONAL_DURATION,
    backend=PLOTTING_BACKEND,
    show_measure_lines=SHOW_MEASURE_LINES,
    display_preview=DISPLAY_PREVIEW,
    preview_rows=PREVIEW_ROWS,
    cleanup_remote=CLEANUP_REMOTE,
    return_plots=RETURN_PLOTS,
)

# Show quick summary
print('Parsed DataFrames:')
for item in results:
    name = item['name']
    df = item['df']
    pos_dur = df.loc[df['Duration'] > 0, 'Duration'] if 'Duration' in df.columns else None
    min_dur_str = str(float(pos_dur.min())) if pos_dur is not None and len(pos_dur) > 0 else 'n/a'
    print(f"- {name}: rows={len(df)}, unique_pitches={df['MIDI'].nunique()}, min_duration={min_dur_str}")

Processing: PrJode_Jos0302_COM_1-5_MissaDapac_002_00006.xml -> 00_prjode_jos0302_com_1_5_missadapac_002_00006

    Measure  Local Onset  Global Onset  Duration Pitch  MIDI
0         1          0.0           0.0       8.0    G3    55
1         1          8.0           8.0       4.0    F3    53
2         2          0.0          12.0       8.0    G4    67
3         2          0.0          12.0       3.0    G3    55
4         2          3.0          15.0       1.0    A3    57
5         2          4.0          16.0       2.0   B-3    58
6         2          6.0          18.0       2.0    G3    55
7         2          8.0          20.0       4.0    F4    65
8         2          8.0          20.0       4.0    A3    57
9         3          0.0          24.0       3.0    G4    67
10        3          0.0          24.0       1.0    G3    55
11        3          0.0          24.0       8.0    G3    55
12        3          1.0          25.0       1.0    A3    57
13        3          2.0          26.0       1.0   B-3    58
14        3          3.0          27.0       1.0    A4    69
15        3          3.0          27.0       1.0    C4    60
16        3          4.0          28.0       2.0   B-4    70
17        3          4.0          28.0       2.0    D4    62
18        3          6.0          30.0       2.0    G4    67
19        3          6.0          30.0       2.0    E4    64

Rows: 797, unique pitches: 24
Processing: wtc1f04.krn -> 01_wtc1f04

    Measure  Local Onset  Global Onset  Duration Pitch  MIDI
0         1          0.0           0.0       4.0   C#3    49
1         2          0.0           4.0       2.0   B#2    48
2         2          2.0           6.0       2.0    E3    52
3         3          0.0           8.0       4.0   D#3    51
4         4          0.0          12.0       4.0   G#3    56
5         4          0.0          12.0       1.0   C#3    49
6         4          1.0          13.0       1.0   D#3    51
7         4          2.0          14.0       2.0    E3    52
8         5          0.0          16.0       2.0  F##3    55
9         5          0.0          16.0       1.0    E3    52
10        5          1.0          17.0       0.5   D#3    51
11        5          1.5          17.5       0.5   C#3    49
12        5          2.0          18.0       2.0    B3    59
13        5          2.0          18.0       1.0   D#3    51
14        5          3.0          19.0       1.0   G#3    56
15        6          0.0          20.0       4.0   A#3    58
16        6          0.0          20.0       1.0   C#3    49
17        6          1.0          21.0       0.5   D#3    51
18        6          1.5          21.5       0.5    E3    52
19        6          2.0          22.0       2.0   F#3    54

Rows: 1429, unique pitches: 45
Parsed DataFrames:
- 00_prjode_jos0302_com_1_5_missadapac_002_00006: rows=797, unique_pitches=24, min_duration=0.5
- 01_wtc1f04: rows=1429, unique_pitches=45, min_duration=0.5

list all parsed dfs:

In [2]:
list(dfs_by_name)

['00_prjode_jos0302_com_1_5_missadapac_002_00006', '01_wtc1f04']

select one parsed df from list:

In [3]:
df0 = results[0]['df']
measure_offsets0 = results[0]['measure_offsets']

display(df0)

     Measure  Local Onset  Global Onset  Duration Pitch  MIDI
0          1          0.0           0.0       8.0    G3    55
1          1          8.0           8.0       4.0    F3    53
2          2          0.0          12.0       8.0    G4    67
3          2          0.0          12.0       3.0    G3    55
4          2          3.0          15.0       1.0    A3    57
..       ...          ...           ...       ...   ...   ...
792       63         11.0         667.0       1.0    E4    64
793       64          0.0         668.0      12.0    G4    67
794       64          0.0         668.0      12.0    D4    62
795       64          0.0         668.0      12.0    G3    55
796       64          0.0         668.0      12.0    G2    43

[797 rows x 6 columns]

save df as tsv:

In [4]:
import os
from datetime import datetime

# Define the path for the /tsv subfolder
output_directory = 'tsv'

# Check if the directory exists; if not, create it
if not os.path.exists(output_directory):
    os.makedirs(output_directory)

# Define the filename path to save inside the /tsv subfolder
filename = os.path.join(output_directory, 'test.tsv')

try:
    df0.to_csv(filename, sep='\t', index=False)
    print(f"Data saved successfully to {os.path.abspath(filename)} at {datetime.now()}.")
except:
    print("Error: data could not be saved.")

Data saved successfully to c:\Users\egorp\Nextcloud\code\public_repos\camat_v2\CAMAT_revamped\tsv\test.tsv at 2025-09-21 01:52:29.318456.