latest parser version with ALL available options

In [ ]:
# Imports
import os
import sys
from IPython.display import display
from pathlib import Path

# Find the nearest directory that contains 'py_scripts' and add it to sys.path
cwd = Path(os.getcwd()).resolve()
for base in [cwd, *cwd.parents]:
    if (base / "py_scripts").is_dir():
        sys.path.insert(0, str(base))
        break
else:
    raise ImportError(f"Could not find a 'py_scripts' directory above {cwd}")

from py_scripts.parser_registry import parse_files


def expand_file_sources(sources: list) -> list:
    """
    Expand FILE_SOURCES list by reading any .txt files and extracting URLs/paths.
    
    - If a source ends with '.txt', read the file and extract all non-empty, 
      non-comment lines (lines not starting with '#').
    - Supports both relative paths (resolved from notebook location) and absolute paths.
    - Other sources (URLs, direct file paths) are passed through unchanged.
    
    Returns a flat list of all expanded sources.
    """
    expanded = []
    notebook_dir = Path(os.getcwd()).resolve()
    
    for source in sources:
        source = source.strip()
        if not source:
            continue
            
        # Check if this is a .txt file (not a URL)
        if source.lower().endswith('.txt') and not source.startswith(('http://', 'https://')):
            # Resolve the path (handle both relative and absolute)
            txt_path = Path(source)
            if not txt_path.is_absolute():
                txt_path = notebook_dir / txt_path
            txt_path = txt_path.resolve()
            
            if txt_path.exists():
                count_before = len(expanded)
                print(f"📄 Expanding sources from: {txt_path}")
                with open(txt_path, 'r', encoding='utf-8') as f:
                    for line in f:
                        line = line.strip()
                        # Skip empty lines and comments
                        if line and not line.startswith('#'):
                            expanded.append(line)
                print(f"   → Found {len(expanded) - count_before} sources")
            else:
                print(f"⚠️ Warning: txt file not found: {txt_path}")
        else:
            # Regular URL or file path - pass through
            expanded.append(source)
    
    return expanded


# Backend selection ('music21' | 'partitura')
PARSING_BACKEND = 'partitura'

# Configuration
FILTER_ZERO_DURATION = True # filter out notes with duration 0 (grace notes)
ADJUST_FRACTIONAL_DURATION = True # rounds Duration, Local Onset, and Global Onset to 3 decimals
PARSE_ENHARMONIC = True     # add 'Pitch Enharmonic' column grounded in source notation
PLOTTING_BACKEND = 'bokeh'  # 'plt' | 'bokeh' | 'none'

SHOW_MEASURE_LINES = True   # draw vertical measure lines at measure starts
MEASURE_LINE_COLOR = 'black'  # color for the measure lines

HOVER_ENABLED = True        # enable hover tool (Bokeh only)
HOVER_FIELDS = ['measure', 'local_onset', 'global_onset', 'duration', 'pitch', 'pitch_enharmonic', 'midi', 'voice', 'xml_id'] # hover options as list

DISPLAY_PREVIEW = True      # show a preview of the parsed data as df
PREVIEW_ROWS = 20          # number of rows to show in the preview

CLEANUP_REMOTE = True       # if source is a URL, delete temp file after parsing
RETURN_PLOTS = False        # include plot objects in results under 'plot'
STRIP_TIES = True           # merge tied notes into single notes (music21 backend only)
ALIGN_ACCIDENT_SCHEMA = True # align accidentals on both parsing backends to the same schema (Pitch Enharmonic is parsed only in b/# format)

COLORIZE_VOICES = True      # color-code notes by voice/part in the piano roll
PALETTE = 'Category20'      # palette name ('Category10'/'tab10', 'Category20'/'tab20', 'Set3', or a list)
INCLUDE_XML_IDS = True      # if MEI, include xml:id per note as 'xml_id' column

# List of file sources (URLs or local paths)

# USAGE EXAMPLES:

# Use the txt file with relative path (relative to notebook location)
# FILE_SOURCES = [
#     '../../test_corpus/test_corpus_links.txt'
# ]

# # Or with absolute path
# FILE_SOURCES = [
#     'C:/Users/egorp/Nextcloud/code/public_repos/camat_v2/test_corpus/test_corpus_links.txt'
# ]

# # Mix txt files with direct URLs
# FILE_SOURCES = [
#     '../../test_corpus/test_corpus_links.txt',
#     'https://raw.githubusercontent.com/music-encoding/sample-encodings/main/MEI_5.0/Music/Complete_examples/Bach-JS_Ein_feste_Burg.mei'
# ]


FILE_SOURCES = [
    '../../test_corpus/test_corpus_links.txt'
    # 'https://raw.githubusercontent.com/music-encoding/sample-encodings/main/MEI_5.0/Music/Complete_examples/Bach-JS_Ein_feste_Burg.mei',
    # 'https://raw.githubusercontent.com/music-encoding/sample-encodings/main/MEI_3.0/Music/Complete_examples/Mozart_Fuge_G_minor.mei',
    # 'C:/Users/egorp/OneDrive/Desktop/weimar_ftp_backup/dokuwiki/database/05/CaSe_11_UNSP_UNSP_Danksagenw_005_00011.xml'  # If you prefer backslashes, make it a raw string: r'C\Users\egorp\...'
]

# Expand FILE_SOURCES (resolves .txt files into their contained URLs/paths)
EFFECTIVE_FILE_SOURCES = expand_file_sources(FILE_SOURCES)

# Plot sizing
PLOT_SIZE_X = 900  # width in pixels
PLOT_SIZE_Y = 600   # height in pixels

# Zoom tool dimensions: 'both' | 'width' (x-only) | 'height' (y-only)
# Bokeh only!
ZOOM_DRAG_DIM = 'both'
ZOOM_WHEEL_DIM = 'width'

# Parse and visualize
results, dfs_by_name, df_processed = parse_files(
    EFFECTIVE_FILE_SOURCES,
    parsing_backend=PARSING_BACKEND,
    filter_zero_duration=FILTER_ZERO_DURATION,
    adjust_fractional_duration=ADJUST_FRACTIONAL_DURATION,
    parse_enharmonic=PARSE_ENHARMONIC,
    backend=PLOTTING_BACKEND,
    show_measure_lines=SHOW_MEASURE_LINES,
    measure_line_color=MEASURE_LINE_COLOR,
    show_hover=HOVER_ENABLED,
    hover_fields=HOVER_FIELDS,
    display_preview=DISPLAY_PREVIEW,
    preview_rows=PREVIEW_ROWS,
    cleanup_remote=CLEANUP_REMOTE,
    return_plots=RETURN_PLOTS,
    plot_width=PLOT_SIZE_X,
    plot_height=PLOT_SIZE_Y,
    zoom_drag_dim=ZOOM_DRAG_DIM,
    zoom_wheel_dim=ZOOM_WHEEL_DIM,
    strip_ties=STRIP_TIES,
    align_accident_schema=ALIGN_ACCIDENT_SCHEMA,
    colorize_voices=COLORIZE_VOICES,
    palette=PALETTE,
    include_xml_ids=INCLUDE_XML_IDS
)

# Show quick summary
print('Parsed DataFrames:')
for item in results:
    name = item['name']
    df = item['df']
    pos_dur = df.loc[df['Duration'] > 0, 'Duration'] if 'Duration' in df.columns else None
    min_dur_str = str(float(pos_dur.min())) if pos_dur is not None and len(pos_dur) > 0 else 'n/a'
    voice_count = df['Voice'].nunique() if 'Voice' in df.columns else 0
    voice_names = sorted(df['Voice'].unique().tolist()) if 'Voice' in df.columns else []
    print(f"- {name}: rows={len(df)}, unique_pitches={df['MIDI'].nunique()}, min_duration={min_dur_str}, voices={voice_count} ({voice_names})")

📄 Expanding sources from: C:\Users\egorp\Nextcloud\code\public_repos\camat_v2\test_corpus\test_corpus_links.txt
   → Found 40 sources

Parsing files:   0%|          | 0/40 [00:00<?, ?file/s]

Processing (partitura): sonata29-1.krn -> 00_sonata29_1
An error occurred while processing https://raw.githubusercontent.com/craigsapp/beethoven-piano-sonatas/master/kern/sonata29-1.krn: list index out of range
Processing (partitura): sonata29-2.krn -> 01_sonata29_2

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,0,2.00,-1.00,0.75,A#3,Bb3,58,P0 - Voice 1,<NA>
1,0,2.00,-1.00,0.75,D4,D4,62,P0 - Voice 1,<NA>
2,0,2.00,-1.00,0.75,D5,D5,74,P0 - Voice 3,<NA>
3,0,2.75,-0.25,0.25,F3,F3,53,P0 - Voice 1,<NA>
4,0,2.75,-0.25,0.25,C4,C4,60,P0 - Voice 1,<NA>
5,0,2.75,-0.25,0.25,A4,A4,69,P0 - Voice 3,<NA>
6,0,2.75,-0.25,0.25,F5,F5,77,P0 - Voice 3,<NA>
7,0,0.00,0.00,1.00,A3,A3,57,P0 - Voice 1,<NA>
8,0,0.00,0.00,1.00,C4,C4,60,P0 - Voice 1,<NA>
9,0,0.00,0.00,1.00,C5,C5,72,P0 - Voice 3,<NA>
10,0,0.00,0.00,1.00,F5,F5,77,P0 - Voice 3,<NA>
11,0,1.00,1.00,0.50,A#3,Bb3,58,P0 - Voice 1,<NA>
12,0,1.00,1.00,0.50,D4,D4,62,P0 - Voice 1,<NA>
13,0,1.00,1.00,0.50,F4,F4,65,P0 - Voice 3,<NA>
14,0,1.00,1.00,0.50,D5,D5,74,P0 - Voice 3,<NA>
15,0,2.00,2.00,0.75,A#4,Bb4,70,P0 - Voice 3,<NA>
16,0,2.00,2.00,0.75,G3,G3,55,P0 - Voice 1,<NA>
17,0,2.00,2.00,0.75,A#3,Bb3,58,P0 - Voice 1,<NA>
18,0,2.75,2.75,0.25,D3,D3,50,P0 - Voice 1,<NA>
19,0,2.75,2.75,0.25,A3,A3,57,P0 - Voice 1,<NA>

Rows: 2001, unique pitches: 70
Processing (partitura): sonata29-3.krn -> 02_sonata29_3

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.0,0.0,1.5,A1,A1,33,P0 - Voice 1,<NA>
1,1,0.0,0.0,1.5,A2,A2,45,P0 - Voice 1,<NA>
2,1,0.0,0.0,1.5,A3,A3,57,P0 - Voice 3,<NA>
3,1,1.5,1.5,1.5,C#2,C#2,37,P0 - Voice 1,<NA>
4,1,1.5,1.5,1.5,C#3,C#3,49,P0 - Voice 1,<NA>
5,1,1.5,1.5,1.5,C#4,C#4,61,P0 - Voice 3,<NA>
6,1,3.0,3.0,1.0,C#5,C#5,73,P0 - Voice 3,<NA>
7,1,3.0,3.0,1.0,A4,A4,69,P0 - Voice 3,<NA>
8,1,3.0,3.0,1.0,C#4,C#4,61,P0 - Voice 4,<NA>
9,1,3.0,3.0,1.0,F#4,F#4,66,P0 - Voice 3,<NA>
10,1,3.0,3.0,1.5,C#3,C#3,49,P0 - Voice 1,<NA>
11,1,3.0,3.0,1.5,F#2,F#2,42,P0 - Voice 1,<NA>
12,1,3.0,3.0,1.5,F#3,F#3,54,P0 - Voice 1,<NA>
13,1,4.0,4.0,0.5,A4,A4,69,P0 - Voice 3,<NA>
14,1,4.5,4.5,0.5,F#2,F#2,42,P0 - Voice 1,<NA>
15,1,4.5,4.5,0.5,C#3,C#3,49,P0 - Voice 1,<NA>
16,1,4.5,4.5,0.5,F#3,F#3,54,P0 - Voice 1,<NA>
17,1,4.5,4.5,0.5,C#4,C#4,61,P0 - Voice 3,<NA>
18,1,4.5,4.5,0.5,A4,A4,69,P0 - Voice 3,<NA>
19,1,5.0,5.0,0.5,F#4,F#4,66,P0 - Voice 3,<NA>

Rows: 5265, unique pitches: 70
Processing (partitura): sonata29-4.krn -> 03_sonata29_4

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:295: UserWarning: Input line 49 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  file = np.loadtxt(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.250,0.250,0.083,F2,F2,41,P0 - Voice 1,<NA>
1,1,0.333,0.333,0.083,F3,F3,53,P0 - Voice 1,<NA>
2,1,0.417,0.417,0.083,F3,F3,53,P0 - Voice 3,<NA>
3,1,0.500,0.500,0.083,F4,F4,65,P0 - Voice 3,<NA>
4,1,0.583,0.583,0.083,F4,F4,65,P0 - Voice 1,<NA>
5,1,0.667,0.667,0.083,F5,F5,77,P0 - Voice 1,<NA>
6,1,0.750,0.750,0.083,F5,F5,77,P0 - Voice 3,<NA>
7,1,0.833,0.833,0.167,F6,F6,89,P0 - Voice 3,<NA>
8,1,0.917,0.917,0.083,F1,F1,29,P0 - Voice 1,<NA>
9,1,0.917,0.917,0.083,F2,F2,41,P0 - Voice 1,<NA>
10,1,1.000,1.000,0.375,F6,F6,89,P0 - Voice 3,<NA>
11,1,1.000,1.000,0.375,F5,F5,77,P0 - Voice 3,<NA>
12,1,1.000,1.000,0.375,F1,F1,29,P0 - Voice 1,<NA>
13,1,1.000,1.000,0.375,F2,F2,41,P0 - Voice 1,<NA>
14,1,1.375,1.375,0.125,F5,F5,77,P0 - Voice 3,<NA>
15,1,1.375,1.375,0.125,F6,F6,89,P0 - Voice 3,<NA>
16,1,1.500,1.500,0.250,F5,F5,77,P0 - Voice 3,<NA>
17,1,1.500,1.500,0.250,F6,F6,89,P0 - Voice 3,<NA>
18,1,1.750,1.750,0.250,F3,F3,53,P0 - Voice 1,<NA>
19,1,1.750,1.750,0.250,F2,F2,41,P0 - Voice 1,<NA>

Rows: 6525, unique pitches: 71
Processing (partitura): sonata32-1.krn -> 04_sonata32_1

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,0,3.875,-0.125,0.125,D#3,Eb3,51,P0 - Voice 1,<NA>
1,0,3.875,-0.125,0.125,D#4,Eb4,63,P0 - Voice 1,<NA>
2,0,0.000,0.000,0.875,F#2,F#2,42,P0 - Voice 1,<NA>
3,0,0.000,0.000,0.875,F#3,F#3,54,P0 - Voice 1,<NA>
4,0,0.875,0.875,0.125,F#1,F#1,30,P0 - Voice 1,<NA>
5,0,0.875,0.875,0.125,F#2,F#2,42,P0 - Voice 1,<NA>
6,0,0.875,0.875,0.125,D#4,Eb4,63,P0 - Voice 3,<NA>
7,0,0.875,0.875,0.125,A4,A4,69,P0 - Voice 3,<NA>
8,0,0.875,0.875,0.125,C5,C5,72,P0 - Voice 3,<NA>
9,0,0.875,0.875,0.125,D#5,Eb5,75,P0 - Voice 3,<NA>
10,0,1.000,1.000,1.000,D#5,Eb5,75,P0 - Voice 3,<NA>
11,0,1.000,1.000,1.000,C5,C5,72,P0 - Voice 3,<NA>
12,0,1.000,1.000,1.000,A4,A4,69,P0 - Voice 3,<NA>
13,0,1.000,1.000,1.000,F#3,F#3,54,P0 - Voice 1,<NA>
14,0,1.000,1.000,1.000,F#2,F#2,42,P0 - Voice 1,<NA>
15,0,1.000,1.000,1.000,D#4,Eb4,63,P0 - Voice 3,<NA>
16,0,2.000,2.000,0.875,F#2,F#2,42,P0 - Voice 1,<NA>
17,0,2.000,2.000,0.875,F#3,F#3,54,P0 - Voice 1,<NA>
18,0,2.000,2.000,0.875,D#4,Eb4,63,P0 - Voice 3,<NA>
19,0,2.000,2.000,0.875,A4,A4,69,P0 - Voice 3,<NA>

Rows: 4063, unique pitches: 73
Processing (partitura): sonata32-2.krn -> 05_sonata32_2

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,0,1.50,-0.75,0.75,C2,C2,36,P0 - Voice 1,<NA>
1,0,1.50,-0.75,0.75,G2,G2,43,P0 - Voice 1,<NA>
2,0,1.50,-0.75,0.75,E4,E4,64,P0 - Voice 4,<NA>
3,0,1.50,-0.75,0.50,C5,C5,72,P0 - Voice 3,<NA>
4,0,2.00,-0.25,0.25,G4,G4,67,P0 - Voice 3,<NA>
5,0,0.00,0.00,0.75,C2,C2,36,P0 - Voice 1,<NA>
6,0,0.00,0.00,0.75,G2,G2,43,P0 - Voice 1,<NA>
7,0,0.00,0.00,0.75,E4,E4,64,P0 - Voice 4,<NA>
8,0,0.00,0.00,1.50,G4,G4,67,P0 - Voice 3,<NA>
9,0,0.75,0.75,0.75,F4,F4,65,P0 - Voice 4,<NA>
10,0,0.75,0.75,0.75,G2,G2,43,P0 - Voice 1,<NA>
11,0,0.75,0.75,0.75,D2,D2,38,P0 - Voice 1,<NA>
12,0,1.50,1.50,0.75,B1,B1,35,P0 - Voice 1,<NA>
13,0,1.50,1.50,0.75,G2,G2,43,P0 - Voice 1,<NA>
14,0,1.50,1.50,0.75,D4,D4,62,P0 - Voice 4,<NA>
15,0,1.50,1.50,0.50,D5,D5,74,P0 - Voice 3,<NA>
16,0,2.00,2.00,0.25,G4,G4,67,P0 - Voice 3,<NA>
17,0,0.00,2.25,0.75,B1,B1,35,P0 - Voice 1,<NA>
18,0,0.00,2.25,0.75,G2,G2,43,P0 - Voice 1,<NA>
19,0,0.00,2.25,0.75,D4,D4,62,P0 - Voice 4,<NA>

Rows: 6012, unique pitches: 70
Processing (partitura): sonata31-1.krn -> 06_sonata31_1

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.00,0.00,1.50,G#2,Ab2,44,P0 - Voice 1,<NA>
1,1,0.00,0.00,1.50,D#3,Eb3,51,P0 - Voice 1,<NA>
2,1,0.00,0.00,1.50,G#4,Ab4,68,P0 - Voice 3,<NA>
3,1,0.00,0.00,1.50,C5,C5,72,P0 - Voice 3,<NA>
4,1,1.50,1.50,0.50,C3,C3,48,P0 - Voice 1,<NA>
5,1,1.50,1.50,0.50,D#3,Eb3,51,P0 - Voice 1,<NA>
6,1,1.50,1.50,0.50,D#4,Eb4,63,P0 - Voice 3,<NA>
7,1,1.50,1.50,0.50,G#4,Ab4,68,P0 - Voice 3,<NA>
8,1,2.00,2.00,0.75,G#4,Ab4,68,P0 - Voice 3,<NA>
9,1,2.00,2.00,0.75,D#4,Eb4,63,P0 - Voice 3,<NA>
10,1,2.00,2.00,0.75,C3,C3,48,P0 - Voice 1,<NA>
11,1,2.00,2.00,0.75,D#3,Eb3,51,P0 - Voice 1,<NA>
12,1,2.75,2.75,0.25,G#4,Ab4,68,P0 - Voice 3,<NA>
13,1,2.75,2.75,0.25,C3,C3,48,P0 - Voice 1,<NA>
14,1,2.75,2.75,0.25,D#3,Eb3,51,P0 - Voice 1,<NA>
15,1,2.75,2.75,0.25,D#4,Eb4,63,P0 - Voice 3,<NA>
16,1,3.00,3.00,1.00,G4,G4,67,P0 - Voice 3,<NA>
17,1,3.00,3.00,1.00,C#5,Db5,73,P0 - Voice 3,<NA>
18,1,3.00,3.00,1.00,A#2,Bb2,46,P0 - Voice 1,<NA>
19,1,3.00,3.00,1.00,D#3,Eb3,51,P0 - Voice 1,<NA>

Rows: 2712, unique pitches: 69
Processing (partitura): sonata31-2.krn -> 07_sonata31_2

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.0,0.0,1.0,F2,F2,41,P0 - Voice 1,<NA>
1,1,0.0,0.0,1.0,F3,F3,53,P0 - Voice 1,<NA>
2,1,0.0,0.0,1.0,G#4,Ab4,68,P0 - Voice 3,<NA>
3,1,0.0,0.0,1.0,C5,C5,72,P0 - Voice 3,<NA>
4,1,1.0,1.0,1.0,G2,G2,43,P0 - Voice 1,<NA>
5,1,1.0,1.0,1.0,G3,G3,55,P0 - Voice 1,<NA>
6,1,1.0,1.0,1.0,E4,E4,64,P0 - Voice 3,<NA>
7,1,1.0,1.0,1.0,A#4,Bb4,70,P0 - Voice 3,<NA>
8,1,2.0,2.0,1.0,G#2,Ab2,44,P0 - Voice 1,<NA>
9,1,2.0,2.0,1.0,G#3,Ab3,56,P0 - Voice 1,<NA>
10,1,2.0,2.0,1.0,F4,F4,65,P0 - Voice 3,<NA>
11,1,2.0,2.0,1.0,G#4,Ab4,68,P0 - Voice 3,<NA>
12,1,3.0,3.0,1.0,G4,G4,67,P0 - Voice 3,<NA>
13,1,3.0,3.0,1.0,E4,E4,64,P0 - Voice 3,<NA>
14,1,3.0,3.0,1.0,C#4,Db4,61,P0 - Voice 3,<NA>
15,1,3.0,3.0,1.0,A#3,Bb3,58,P0 - Voice 1,<NA>
16,1,3.0,3.0,1.0,A#2,Bb2,46,P0 - Voice 1,<NA>
17,1,4.0,4.0,1.0,B2,B2,47,P0 - Voice 1,<NA>
18,1,4.0,4.0,1.0,G#3,Ab3,56,P0 - Voice 3,<NA>
19,1,4.0,4.0,1.0,B3,B3,59,P0 - Voice 1,<NA>

Rows: 966, unique pitches: 62
Processing (partitura): sonata31-3.krn -> 08_sonata31_3

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.000,0.000,0.875,A#1,Bb1,34,P0 - Voice 1,<NA>
1,1,0.000,0.000,0.875,A#2,Bb2,46,P0 - Voice 1,<NA>
2,1,0.000,0.000,0.875,C#5,Db5,73,P0 - Voice 3,<NA>
3,1,0.000,0.000,0.875,F5,F5,77,P0 - Voice 3,<NA>
4,1,0.875,0.875,0.125,A#1,Bb1,34,P0 - Voice 1,<NA>
5,1,0.875,0.875,0.125,A#2,Bb2,46,P0 - Voice 1,<NA>
6,1,0.875,0.875,0.125,C#5,Db5,73,P0 - Voice 3,<NA>
7,1,0.875,0.875,0.125,F5,F5,77,P0 - Voice 3,<NA>
8,1,1.000,1.000,0.500,A#1,Bb1,34,P0 - Voice 1,<NA>
9,1,1.000,1.000,0.500,A#2,Bb2,46,P0 - Voice 1,<NA>
10,1,1.000,1.000,0.500,D#5,Eb5,75,P0 - Voice 4,<NA>
11,1,1.000,1.000,0.500,F#5,Gb5,78,P0 - Voice 4,<NA>
12,1,1.500,1.500,0.500,A4,A4,69,P0 - Voice 4,<NA>
13,1,1.500,1.500,0.500,F#4,Gb4,66,P0 - Voice 4,<NA>
14,1,1.500,1.500,0.500,D#4,Eb4,63,P0 - Voice 4,<NA>
15,1,1.500,1.500,0.500,A#2,Bb2,46,P0 - Voice 1,<NA>
16,1,1.500,1.500,0.500,A#1,Bb1,34,P0 - Voice 1,<NA>
17,1,1.500,1.500,0.500,C4,C4,60,P0 - Voice 4,<NA>
18,1,2.000,2.000,2.000,A#1,Bb1,34,P0 - Voice 1,<NA>
19,1,2.000,2.000,2.000,A#2,Bb2,46,P0 - Voice 1,<NA>

Rows: 3843, unique pitches: 70
Processing (partitura): sonata14-1.krn -> 09_sonata14_1

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:295: UserWarning: Input line 10 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  file = np.loadtxt(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.000,0.000,4.000,C#2,C#2,37,P0 - Voice 1,<NA>
1,1,0.000,0.000,4.000,C#3,C#3,49,P0 - Voice 1,<NA>
2,1,0.000,0.000,0.333,G#3,G#3,56,P0 - Voice 4,<NA>
3,1,0.333,0.333,0.333,C#4,C#4,61,P0 - Voice 4,<NA>
4,1,0.667,0.667,0.333,E4,E4,64,P0 - Voice 4,<NA>
5,1,1.000,1.000,0.333,G#3,G#3,56,P0 - Voice 4,<NA>
6,1,1.333,1.333,0.333,C#4,C#4,61,P0 - Voice 4,<NA>
7,1,1.667,1.667,0.333,E4,E4,64,P0 - Voice 4,<NA>
8,1,2.000,2.000,0.333,G#3,G#3,56,P0 - Voice 4,<NA>
9,1,2.333,2.333,0.333,C#4,C#4,61,P0 - Voice 4,<NA>
10,1,2.667,2.667,0.333,E4,E4,64,P0 - Voice 4,<NA>
11,1,3.000,3.000,0.333,G#3,G#3,56,P0 - Voice 4,<NA>
12,1,3.333,3.333,0.333,C#4,C#4,61,P0 - Voice 4,<NA>
13,1,3.667,3.667,0.333,E4,E4,64,P0 - Voice 4,<NA>
14,1,4.000,4.000,4.000,B1,B1,35,P0 - Voice 1,<NA>
15,1,4.000,4.000,4.000,B2,B2,47,P0 - Voice 1,<NA>
16,1,4.000,4.000,0.333,G#3,G#3,56,P0 - Voice 4,<NA>
17,1,4.333,4.333,0.333,C#4,C#4,61,P0 - Voice 4,<NA>
18,1,4.667,4.667,0.333,E4,E4,64,P0 - Voice 4,<NA>
19,1,5.000,5.000,0.333,G#3,G#3,56,P0 - Voice 4,<NA>

Rows: 1182, unique pitches: 55
Processing (partitura): sonata14-2.krn -> 10_sonata14_2

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:295: UserWarning: Input line 50 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  file = np.loadtxt(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,0,2.0,-1.0,1.0,F4,F4,65,P0 - Voice 1,<NA>
1,0,2.0,-1.0,1.0,G#4,Ab4,68,P0 - Voice 3,<NA>
2,0,2.0,-1.0,1.0,C#5,Db5,73,P0 - Voice 3,<NA>
3,0,0.0,0.0,2.0,D#4,Eb4,63,P0 - Voice 1,<NA>
4,0,0.0,0.0,2.0,G#4,Ab4,68,P0 - Voice 3,<NA>
5,0,0.0,0.0,2.0,C5,C5,72,P0 - Voice 3,<NA>
6,0,2.0,2.0,1.0,C#4,Db4,61,P0 - Voice 1,<NA>
7,0,2.0,2.0,1.0,G4,G4,67,P0 - Voice 3,<NA>
8,0,2.0,2.0,1.0,A#4,Bb4,70,P0 - Voice 3,<NA>
9,0,0.0,3.0,1.0,C4,C4,60,P0 - Voice 1,<NA>
10,0,0.0,3.0,1.0,G#4,Ab4,68,P0 - Voice 3,<NA>
11,0,0.0,3.0,1.0,D#5,Eb5,75,P0 - Voice 3,<NA>
12,0,2.0,5.0,1.0,C#5,Db5,73,P0 - Voice 3,<NA>
13,0,2.0,5.0,1.0,F4,F4,65,P0 - Voice 3,<NA>
14,0,2.0,5.0,1.0,C#3,Db3,49,P0 - Voice 1,<NA>
15,0,2.0,5.0,1.0,A#3,Bb3,58,P0 - Voice 1,<NA>
16,0,0.0,6.0,1.0,D#3,Eb3,51,P0 - Voice 1,<NA>
17,0,0.0,6.0,1.0,D#4,Eb4,63,P0 - Voice 1,<NA>
18,0,0.0,6.0,1.0,G#4,Ab4,68,P0 - Voice 3,<NA>
19,0,0.0,6.0,1.0,C5,C5,72,P0 - Voice 3,<NA>

Rows: 430, unique pitches: 37
Processing (partitura): sonata14-3.krn -> 11_sonata14_3

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:295: UserWarning: Input line 66 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  file = np.loadtxt(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.00,0.00,0.50,C#2,C#2,37,P0 - Voice 1,<NA>
1,1,0.25,0.25,0.25,G#2,G#2,44,P0 - Voice 3,<NA>
2,1,0.50,0.50,0.50,G#2,G#2,44,P0 - Voice 1,<NA>
3,1,0.50,0.50,0.25,C#3,C#3,49,P0 - Voice 3,<NA>
4,1,0.75,0.75,0.25,E3,E3,52,P0 - Voice 3,<NA>
5,1,1.00,1.00,0.50,C#2,C#2,37,P0 - Voice 1,<NA>
6,1,1.00,1.00,0.25,G#3,G#3,56,P0 - Voice 3,<NA>
7,1,1.25,1.25,0.25,C#3,C#3,49,P0 - Voice 3,<NA>
8,1,1.50,1.50,0.25,E3,E3,52,P0 - Voice 3,<NA>
9,1,1.50,1.50,0.50,G#2,G#2,44,P0 - Voice 1,<NA>
10,1,1.75,1.75,0.25,G#3,G#3,56,P0 - Voice 3,<NA>
11,1,2.00,2.00,0.50,C#2,C#2,37,P0 - Voice 1,<NA>
12,1,2.00,2.00,0.25,C#4,C#4,61,P0 - Voice 3,<NA>
13,1,2.25,2.25,0.25,E3,E3,52,P0 - Voice 3,<NA>
14,1,2.50,2.50,0.50,G#2,G#2,44,P0 - Voice 1,<NA>
15,1,2.50,2.50,0.25,G#3,G#3,56,P0 - Voice 3,<NA>
16,1,2.75,2.75,0.25,C#4,C#4,61,P0 - Voice 3,<NA>
17,1,3.00,3.00,0.25,E4,E4,64,P0 - Voice 3,<NA>
18,1,3.00,3.00,0.50,C#2,C#2,37,P0 - Voice 1,<NA>
19,1,3.25,3.25,0.25,G#3,G#3,56,P0 - Voice 3,<NA>

Rows: 4924, unique pitches: 60
Processing (partitura): 010-1_etiuda_c-dur_op_10_nr_1.krn -> 12_010_1_etiuda_c_dur_op_10_nr_1
An error occurred while processing https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/010-1_etiuda_c-dur_op_10_nr_1.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/010-1_etiuda_c-dur_op_10_nr_1.krn
Processing (partitura): 010-2_etiuda_a-moll_op_10_nr_2.krn -> 13_010_2_etiuda_a_moll_op_10_nr_2
An error occurred while processing https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/010-2_etiuda_a-moll_op_10_nr_2.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/010-2_etiuda_a-moll_op_10_nr_2.krn
Processing (partitura): 025-11_etiuda_a-moll_op_25_nr_11.krn -> 14_025_11_etiuda_a_moll_op_25_nr_11
An error occurred while processing https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/025-11_etiuda_a-moll_op_25_nr_11.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/025-11_etiuda_a-moll_op_25_nr_11.krn
Processing (partitura): 025-12_etiuda_c-moll_op_25_nr_12.krn -> 15_025_12_etiuda_c_moll_op_25_nr_12
An error occurred while processing https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/025-12_etiuda_c-moll_op_25_nr_12.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/025-12_etiuda_c-moll_op_25_nr_12.krn
Processing (partitura): 023_ballada_g-moll_op_23.krn -> 16_023_ballada_g_moll_op_23
An error occurred while processing https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/023_ballada_g-moll_op_23.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/023_ballada_g-moll_op_23.krn
Processing (partitura): 052_ballada_f-moll_op_52.krn -> 17_052_ballada_f_moll_op_52
An error occurred while processing https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/052_ballada_f-moll_op_52.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/pl-wnifc/humdrum-chopin-first-editions/master/kern/052_ballada_f-moll_op_52.krn
Processing (partitura): wtc1p24.krn -> 18_wtc1p24
An error occurred while processing https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1p24.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1p24.krn
Processing (partitura): wtc1f24.krn -> 19_wtc1f24
An error occurred while processing https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1f24.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1f24.krn
Processing (partitura): wtc1p18.krn -> 20_wtc1p18
An error occurred while processing https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1p18.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1p18.krn
Processing (partitura): wtc1f18.krn -> 21_wtc1f18
An error occurred while processing https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1f18.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1f18.krn
Processing (partitura): wtc1p22.krn -> 22_wtc1p22
An error occurred while processing https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1p22.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1p22.krn
Processing (partitura): wtc1f22.krn -> 23_wtc1f22
An error occurred while processing https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1f22.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1f22.krn
Processing (partitura): wtc1p04.krn -> 24_wtc1p04
An error occurred while processing https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1p04.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1p04.krn
Processing (partitura): wtc1f04.krn -> 25_wtc1f04
An error occurred while processing https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1f04.krn: Error downloading the file: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/craigsapp/bach-wtc/master/kern/wtc1f04.krn
Processing (partitura): sonata14-1.krn -> 26_sonata14_1

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:295: UserWarning: Input line 67 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  file = np.loadtxt(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.00,0.00,2.00,C2,C2,36,P0 - Voice 1,<NA>
1,1,0.00,0.00,2.00,C3,C3,48,P0 - Voice 1,<NA>
2,1,0.00,0.00,2.00,C4,C4,60,P0 - Voice 3,<NA>
3,1,2.00,2.00,1.00,D#2,Eb2,39,P0 - Voice 1,<NA>
4,1,2.00,2.00,1.00,D#3,Eb3,51,P0 - Voice 1,<NA>
5,1,2.00,2.00,1.00,D#4,Eb4,63,P0 - Voice 3,<NA>
6,1,3.00,3.00,1.00,G2,G2,43,P0 - Voice 1,<NA>
7,1,3.00,3.00,1.00,G3,G3,55,P0 - Voice 1,<NA>
8,1,3.00,3.00,1.00,G4,G4,67,P0 - Voice 3,<NA>
9,1,4.00,4.00,1.00,C3,C3,48,P0 - Voice 1,<NA>
10,1,4.00,4.00,1.00,C4,C4,60,P0 - Voice 1,<NA>
11,1,4.00,4.00,1.00,C5,C5,72,P0 - Voice 3,<NA>
12,1,5.00,5.00,1.00,D#3,Eb3,51,P0 - Voice 1,<NA>
13,1,5.00,5.00,1.00,D#4,Eb4,63,P0 - Voice 1,<NA>
14,1,5.00,5.00,1.00,D#5,Eb5,75,P0 - Voice 3,<NA>
15,1,6.75,6.75,0.25,D#5,Eb5,75,P0 - Voice 3,<NA>
16,1,7.00,7.00,0.50,D#5,Eb5,75,P0 - Voice 3,<NA>
17,1,7.50,7.50,0.25,D5,D5,74,P0 - Voice 3,<NA>
18,1,7.75,7.75,0.25,D#5,Eb5,75,P0 - Voice 3,<NA>
19,1,8.00,8.00,1.00,G5,G5,79,P0 - Voice 3,<NA>

Rows: 2170, unique pitches: 59
Processing (partitura): sonata14-2.krn -> 27_sonata14_2

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.000,0.000,0.250,D#3,Eb3,51,P0 - Voice 1,<NA>
1,1,0.000,0.000,1.000,A#4,Bb4,70,P0 - Voice 3,<NA>
2,1,0.250,0.250,0.250,G3,G3,55,P0 - Voice 1,<NA>
3,1,0.500,0.500,0.250,A#3,Bb3,58,P0 - Voice 1,<NA>
4,1,0.750,0.750,0.250,G3,G3,55,P0 - Voice 1,<NA>
5,1,1.000,1.000,0.250,D#3,Eb3,51,P0 - Voice 1,<NA>
6,1,1.000,1.000,0.500,G4,G4,67,P0 - Voice 3,<NA>
7,1,1.250,1.250,0.250,G3,G3,55,P0 - Voice 1,<NA>
8,1,1.500,1.500,0.250,A#3,Bb3,58,P0 - Voice 1,<NA>
9,1,1.500,1.500,0.500,G4,G4,67,P0 - Voice 3,<NA>
10,1,1.750,1.750,0.250,G3,G3,55,P0 - Voice 1,<NA>
11,1,2.000,2.000,1.000,D#4,Eb4,63,P0 - Voice 4,<NA>
12,1,2.000,2.000,0.875,G4,G4,67,P0 - Voice 3,<NA>
13,1,2.000,2.000,0.250,A#2,Bb2,46,P0 - Voice 1,<NA>
14,1,2.250,2.250,0.250,D#3,Eb3,51,P0 - Voice 1,<NA>
15,1,2.500,2.500,0.250,G3,G3,55,P0 - Voice 1,<NA>
16,1,2.750,2.750,0.250,D#3,Eb3,51,P0 - Voice 1,<NA>
17,1,2.875,2.875,0.125,G#4,Ab4,68,P0 - Voice 3,<NA>
18,1,3.000,3.000,0.250,A#2,Bb2,46,P0 - Voice 1,<NA>
19,1,3.000,3.000,0.500,D4,D4,62,P0 - Voice 4,<NA>

Rows: 1870, unique pitches: 54
Processing (partitura): sonata14-3.krn -> 28_sonata14_3

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,0,2.0,-1.0,2.0,G5,G5,79,P0 - Voice 3,<NA>
1,0,0.0,0.0,3.0,C4,C4,60,P0 - Voice 1,<NA>
2,0,0.0,0.0,3.0,D#4,Eb4,63,P0 - Voice 1,<NA>
3,0,1.0,1.0,1.0,D#5,Eb5,75,P0 - Voice 3,<NA>
4,0,2.0,2.0,2.0,C5,C5,72,P0 - Voice 3,<NA>
5,0,0.0,3.0,3.0,D4,D4,62,P0 - Voice 1,<NA>
6,0,0.0,3.0,3.0,F4,F4,65,P0 - Voice 1,<NA>
7,0,1.0,4.0,1.0,B4,B4,71,P0 - Voice 3,<NA>
8,0,2.0,5.0,2.0,G#5,Ab5,80,P0 - Voice 3,<NA>
9,0,0.0,6.0,3.0,B3,B3,59,P0 - Voice 1,<NA>
10,0,0.0,6.0,3.0,D4,D4,62,P0 - Voice 1,<NA>
11,0,1.0,7.0,1.0,G5,G5,79,P0 - Voice 3,<NA>
12,0,2.0,8.0,2.0,F5,F5,77,P0 - Voice 3,<NA>
13,0,0.0,9.0,3.0,C4,C4,60,P0 - Voice 1,<NA>
14,0,0.0,9.0,3.0,G4,G4,67,P0 - Voice 1,<NA>
15,0,1.0,10.0,1.0,D#5,Eb5,75,P0 - Voice 3,<NA>
16,0,2.0,11.0,2.0,G5,G5,79,P0 - Voice 3,<NA>
17,0,0.0,12.0,2.0,D#4,Eb4,63,P0 - Voice 2,<NA>
18,0,0.0,12.0,3.0,G4,G4,67,P0 - Voice 1,<NA>
19,0,1.0,13.0,1.0,C6,C6,84,P0 - Voice 3,<NA>

Rows: 2192, unique pitches: 59
Processing (partitura): sonata08-1.krn -> 29_sonata08_1

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:295: UserWarning: Input line 64 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  file = np.loadtxt(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.00,0.00,0.50,A3,A3,57,P0 - Voice 1,<NA>
1,1,0.00,0.00,0.50,C4,C4,60,P0 - Voice 1,<NA>
2,1,0.00,0.00,0.50,E4,E4,64,P0 - Voice 1,<NA>
3,1,0.00,0.00,1.00,E5,E5,76,P0 - Voice 3,<NA>
4,1,0.50,0.50,0.50,A3,A3,57,P0 - Voice 1,<NA>
5,1,0.50,0.50,0.50,C4,C4,60,P0 - Voice 1,<NA>
6,1,0.50,0.50,0.50,E4,E4,64,P0 - Voice 1,<NA>
7,1,1.00,1.00,0.50,A3,A3,57,P0 - Voice 1,<NA>
8,1,1.00,1.00,0.50,C4,C4,60,P0 - Voice 1,<NA>
9,1,1.00,1.00,0.50,E4,E4,64,P0 - Voice 1,<NA>
10,1,1.00,1.00,0.75,E5,E5,76,P0 - Voice 3,<NA>
11,1,1.50,1.50,0.50,E4,E4,64,P0 - Voice 1,<NA>
12,1,1.50,1.50,0.50,A3,A3,57,P0 - Voice 1,<NA>
13,1,1.50,1.50,0.50,C4,C4,60,P0 - Voice 1,<NA>
14,1,1.75,1.75,0.25,E5,E5,76,P0 - Voice 3,<NA>
15,1,2.00,2.00,0.50,A3,A3,57,P0 - Voice 1,<NA>
16,1,2.00,2.00,0.50,C4,C4,60,P0 - Voice 1,<NA>
17,1,2.00,2.00,0.50,E4,E4,64,P0 - Voice 1,<NA>
18,1,2.00,2.00,1.00,E5,E5,76,P0 - Voice 3,<NA>
19,1,2.50,2.50,0.50,E4,E4,64,P0 - Voice 1,<NA>

Rows: 3231, unique pitches: 55
Processing (partitura): sonata08-2.krn -> 30_sonata08_2

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,0,2.00,-1.00,0.25,F4,F4,65,P0 - Voice 3,<NA>
1,0,2.25,-0.75,0.25,A4,A4,69,P0 - Voice 3,<NA>
2,0,2.50,-0.50,0.25,C5,C5,72,P0 - Voice 3,<NA>
3,0,2.75,-0.25,0.25,F5,F5,77,P0 - Voice 3,<NA>
4,0,0.00,0.00,1.00,F2,F2,41,P0 - Voice 1,<NA>
5,0,0.00,0.00,1.00,F3,F3,53,P0 - Voice 1,<NA>
6,0,0.00,0.00,0.75,A5,A5,81,P0 - Voice 3,<NA>
7,0,0.75,0.75,0.25,F5,F5,77,P0 - Voice 3,<NA>
8,0,1.00,1.00,1.00,A2,A2,45,P0 - Voice 1,<NA>
9,0,1.00,1.00,1.00,A3,A3,57,P0 - Voice 1,<NA>
10,0,1.00,1.00,0.50,C5,C5,72,P0 - Voice 3,<NA>
11,0,1.50,1.50,0.50,A4,A4,69,P0 - Voice 3,<NA>
12,0,1.50,1.50,0.50,C5,C5,72,P0 - Voice 3,<NA>
13,0,2.00,2.00,0.25,C5,C5,72,P0 - Voice 3,<NA>
14,0,2.00,2.00,0.25,A4,A4,69,P0 - Voice 3,<NA>
15,0,2.00,2.00,1.00,C3,C3,48,P0 - Voice 1,<NA>
16,0,2.00,2.00,1.00,C4,C4,60,P0 - Voice 1,<NA>
17,0,2.25,2.25,0.25,G4,G4,67,P0 - Voice 3,<NA>
18,0,2.25,2.25,0.25,A#4,Bb4,70,P0 - Voice 3,<NA>
19,0,2.50,2.50,0.25,F4,F4,65,P0 - Voice 3,<NA>

Rows: 2086, unique pitches: 56
Processing (partitura): sonata08-3.krn -> 31_sonata08_3

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:355: UserWarning: Part P0 already exists. Adding to previous Part.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importkern.py:552: UserWarning: Slurs openings and closings do not match. Skipping parsing slurs for this part P0.
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.0,0.0,1.5,A4,A4,69,P0 - Voice 4,<NA>
1,1,0.0,0.0,1.5,C5,C5,72,P0 - Voice 3,<NA>
2,1,0.5,0.5,1.5,A3,A3,57,P0 - Voice 2,<NA>
3,1,0.5,0.5,0.5,A3,A3,57,P0 - Voice 1,<NA>
4,1,1.0,1.0,0.5,E4,E4,64,P0 - Voice 1,<NA>
5,1,1.5,1.5,0.5,D4,D4,62,P0 - Voice 1,<NA>
6,1,1.5,1.5,0.5,G#4,G#4,68,P0 - Voice 4,<NA>
7,1,1.5,1.5,0.5,B4,B4,71,P0 - Voice 3,<NA>
8,1,2.0,2.0,2.0,E4,E4,64,P0 - Voice 4,<NA>
9,1,2.0,2.0,1.5,A4,A4,69,P0 - Voice 3,<NA>
10,1,2.5,2.5,0.5,A3,A3,57,P0 - Voice 1,<NA>
11,1,2.5,2.5,1.5,A3,A3,57,P0 - Voice 2,<NA>
12,1,3.0,3.0,0.5,C4,C4,60,P0 - Voice 1,<NA>
13,1,3.5,3.5,0.5,G#4,G#4,68,P0 - Voice 3,<NA>
14,1,3.5,3.5,0.5,B3,B3,59,P0 - Voice 1,<NA>
15,1,4.0,4.0,2.0,E4,E4,64,P0 - Voice 4,<NA>
16,1,4.0,4.0,1.5,A4,A4,69,P0 - Voice 3,<NA>
17,1,4.5,4.5,0.5,A3,A3,57,P0 - Voice 1,<NA>
18,1,5.0,5.0,0.5,C4,C4,60,P0 - Voice 1,<NA>
19,1,5.5,5.5,0.5,G#3,G#3,56,P0 - Voice 1,<NA>

Rows: 1858, unique pitches: 52
Processing (partitura): Mozart_Fuge_G_minor.mei -> 32_mozart_fuge_g_minor

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmei.py:255: UserWarning: The key signature is not encoded in None or in any ancestor scoreDef.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmei.py:258: UserWarning: A default key signature of C maj is set.
  warnings.warn("A default key signature of C maj is set.")
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmei.py:1110: UserWarning: Warning : parts have measures of different duration in measure d1e26710
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.00,0.00,2.00,D5,D5,74,P1 - Voice 1,d1e242
1,1,2.00,2.00,1.50,A#4,Bb4,70,P1 - Voice 1,d1e256
2,1,3.50,3.50,0.25,A4,A4,69,P1 - Voice 1,d1e273
3,1,3.75,3.75,0.25,G4,G4,67,P1 - Voice 1,d1e291
4,1,4.00,4.00,0.50,F#4,F#4,66,P1 - Voice 1,d1e391
5,1,4.50,4.50,0.50,G4,G4,67,P1 - Voice 1,d1e411
6,1,5.00,5.00,1.50,A4,A4,69,P1 - Voice 1,d1e427
7,1,6.50,6.50,0.50,D#5,Eb5,75,P1 - Voice 1,d1e442
8,1,7.00,7.00,0.50,D5,D5,74,P1 - Voice 1,d1e460
9,1,7.50,7.50,0.50,C5,C5,72,P1 - Voice 1,d1e476
10,1,8.00,8.00,0.50,A#4,Bb4,70,P1 - Voice 1,d1e515
11,1,8.00,8.00,2.00,G4,G4,67,P2 - Voice 1,d1e630
12,1,8.50,8.50,0.50,A4,A4,69,P1 - Voice 1,d1e533
13,1,9.00,9.00,0.50,A#4,Bb4,70,P1 - Voice 1,d1e549
14,1,9.50,9.50,0.50,C5,C5,72,P1 - Voice 1,d1e567
15,1,10.00,10.00,1.50,F4,F4,65,P2 - Voice 1,d1e644
16,1,10.00,10.00,0.50,D5,D5,74,P1 - Voice 1,d1e583
17,1,10.50,10.50,0.50,A4,A4,69,P1 - Voice 1,d1e599
18,1,11.00,11.00,1.00,D5,D5,74,P1 - Voice 1,d1e615
19,1,11.50,11.50,0.25,E4,E4,64,P2 - Voice 1,d1e659

Rows: 1523, unique pitches: 43
Processing (partitura): Debussy_Golliwogg'sCakewalk.mei -> 33_debussy_golliwogg_scakewalk

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmei.py:255: UserWarning: The key signature is not encoded in None or in any ancestor scoreDef.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmei.py:258: UserWarning: A default key signature of C maj is set.
  warnings.warn("A default key signature of C maj is set.")

An error occurred while processing https://raw.githubusercontent.com/music-encoding/sample-encodings/refs/heads/main/MEI_5.1/Music/Complete_examples/Debussy_Golliwogg'sCakewalk.mei: Tag {http://www.music-encoding.org/ns/mei}mSpace not supported
Processing (partitura): grace_Notes.mei -> 34_grace_notes
An error occurred while processing https://raw.githubusercontent.com/music-encoding/sample-encodings/refs/heads/main/MEI_5.0/Musical-features/snippets/grace_Notes.mei: 'dur'
Processing (partitura): special_features.mei -> 35_special_features

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmei.py:1110: UserWarning: Warning : parts have measures of different duration in measure j1wi35hx
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmei.py:1187: UserWarning: Warning: tie f15e18jg is missing the a startid or endid
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmei.py:1187: UserWarning: Warning: tie pg0dly9 is missing the a startid or endid
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmei.py:1187: UserWarning: Warning: tie qq7tdop is missing the a startid or endid
  warnings.warn(

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.0,0.0,0.5,F4,F4,65,gab4gh9 - Voice 1,m2s1l1e1
1,1,0.5,0.5,0.5,F4,E#4,65,gab4gh9 - Voice 1,m2s1l1e2
2,1,1.0,1.0,1.0,C2,C2,36,qfp3r3j - Voice 1,m2s2l1e2
3,1,1.0,1.0,1.5,A4,A4,69,gab4gh9 - Voice 1,m2s1l1e3
4,1,2.0,2.0,1.0,C3,C3,48,qfp3r3j - Voice 1,m2s2l1e3
5,1,2.0,2.0,1.0,B3,B3,59,gab4gh9 - Voice 2,w15l8fb5
6,1,2.0,2.0,1.0,E4,E4,64,gab4gh9 - Voice 2,m2s1l2e3
7,1,2.5,2.5,0.5,G4,G4,67,gab4gh9 - Voice 1,m2s1l1e4
8,1,3.0,3.0,1.0,C3,C3,48,qfp3r3j - Voice 1,m3s2l1e1
9,1,3.0,3.0,1.0,B3,B3,59,qfp3r3j - Voice 1,m3s2l1e2
10,1,3.0,3.0,1.0,F4,E#4,65,qfp3r3j - Voice 1,m3s2l1e3
11,1,3.0,3.0,0.5,A#4,A#4,70,gab4gh9 - Voice 1,m3s1l1e1
12,1,3.5,3.5,0.5,B4,B4,71,gab4gh9 - Voice 1,m3s1l1e2
13,1,4.0,4.0,0.5,C5,B#4,72,gab4gh9 - Voice 1,m3s1l1e3
14,1,4.5,4.5,1.0,C5,C5,72,gab4gh9 - Voice 2,og1ttju
15,1,4.5,4.5,0.5,C5,C5,72,gab4gh9 - Voice 1,m3s1l1e4
16,1,5.0,5.0,0.5,F5,E#5,77,gab4gh9 - Voice 1,m3s1l1e5
17,1,5.5,5.5,0.5,B4,B4,71,gab4gh9 - Voice 2,m3s1l2e6
18,1,5.5,5.5,0.5,D#5,D#5,75,gab4gh9 - Voice 1,m3s1l1e6
19,1,6.0,6.0,1.0,F2,F2,41,qfp3r3j - Voice 1,m4s2l1e1

Rows: 30, unique pitches: 17
Processing (partitura): Schubert_D911-08.xml -> 36_schubert_d911_08

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmusicxml.py:1065: UserWarning: ignoring direction type: other-direction {'default-y': '-68', 'print-object': 'no'}
  warnings.warn("ignoring direction type: {} {}".format(dt.tag, dt.attrib))

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.00,0.00,0.50,G2,G2,43,Piano - Voice 2,<NA>
1,1,0.00,0.00,0.50,D3,D3,50,Piano - Voice 1,<NA>
2,1,0.25,0.25,0.25,G3,G3,55,Piano - Voice 1,<NA>
3,1,0.25,0.25,0.25,D4,D4,62,Piano - Voice 1,<NA>
4,1,0.50,0.50,0.50,A2,A2,45,Piano - Voice 2,<NA>
5,1,0.50,0.50,0.50,D3,D3,50,Piano - Voice 1,<NA>
6,1,0.75,0.75,0.25,A3,A3,57,Piano - Voice 1,<NA>
7,1,0.75,0.75,0.25,D4,D4,62,Piano - Voice 1,<NA>
8,1,1.00,1.00,0.50,A#2,Bb2,46,Piano - Voice 2,<NA>
9,1,1.00,1.00,0.50,D3,D3,50,Piano - Voice 1,<NA>
10,1,1.25,1.25,0.25,A#3,Bb3,58,Piano - Voice 1,<NA>
11,1,1.25,1.25,0.25,D4,D4,62,Piano - Voice 1,<NA>
12,1,1.50,1.50,0.50,B2,B2,47,Piano - Voice 2,<NA>
13,1,1.50,1.50,0.50,D3,D3,50,Piano - Voice 1,<NA>
14,1,1.75,1.75,0.25,D4,D4,62,Piano - Voice 1,<NA>
15,1,1.75,1.75,0.25,B3,B3,59,Piano - Voice 1,<NA>
16,1,2.00,2.00,0.50,C3,C3,48,Piano - Voice 2,<NA>
17,1,2.00,2.00,0.50,D3,D3,50,Piano - Voice 1,<NA>
18,1,2.25,2.25,0.25,C4,C4,60,Piano - Voice 1,<NA>
19,1,2.25,2.25,0.25,D4,D4,62,Piano - Voice 1,<NA>

Rows: 2048, unique pitches: 41
Processing (partitura): Schubert_D911-20.xml -> 37_schubert_d911_20

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\directions.py:514: UserWarning: error parsing "Mäßig" (UnexpectedCharacters)
  warnings.warn('error parsing "{}" ({})'.format(string, type(e).__name__))
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmusicxml.py:1065: UserWarning: ignoring direction type: other-direction {'default-y': '14', 'print-object': 'no'}
  warnings.warn("ignoring direction type: {} {}".format(dt.tag, dt.attrib))
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmusicxml.py:1065: UserWarning: ignoring direction type: other-direction {'default-y': '-53', 'print-object': 'no'}
  warnings.warn("ignoring direction type: {} {}".format(dt.tag, dt.attrib))

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,1.50,-0.50,0.25,A#3,Bb3,58,Piano - Voice 4,<NA>
1,1,1.50,-0.50,0.25,G4,G4,67,Piano - Voice 1,<NA>
2,1,1.75,-0.25,0.25,C4,C4,60,Piano - Voice 4,<NA>
3,1,1.75,-0.25,0.25,A4,A4,69,Piano - Voice 1,<NA>
4,1,0.00,0.00,0.50,G3,G3,55,Piano - Voice 4,<NA>
5,1,0.00,0.00,0.50,D4,D4,62,Piano - Voice 1,<NA>
6,1,0.00,0.00,0.50,G4,G4,67,Piano - Voice 1,<NA>
7,1,0.00,0.00,0.50,A#4,Bb4,70,Piano - Voice 1,<NA>
8,1,0.50,0.50,0.50,A#4,Bb4,70,Piano - Voice 1,<NA>
9,1,0.50,0.50,0.50,G4,G4,67,Piano - Voice 1,<NA>
10,1,0.50,0.50,0.50,G3,G3,55,Piano - Voice 4,<NA>
11,1,0.50,0.50,0.50,D4,D4,62,Piano - Voice 1,<NA>
12,1,1.00,1.00,0.50,G3,G3,55,Piano - Voice 4,<NA>
13,1,1.00,1.00,0.50,D4,D4,62,Piano - Voice 1,<NA>
14,1,1.00,1.00,0.50,G4,G4,67,Piano - Voice 1,<NA>
15,1,1.00,1.00,0.50,A#4,Bb4,70,Piano - Voice 1,<NA>
16,1,1.50,1.50,0.50,A#4,Bb4,70,Piano - Voice 1,<NA>
17,1,1.50,1.50,0.50,G4,G4,67,Piano - Voice 1,<NA>
18,1,1.50,1.50,0.50,G3,G3,55,Piano - Voice 4,<NA>
19,1,1.50,1.50,0.50,D4,D4,62,Piano - Voice 1,<NA>

Rows: 1131, unique pitches: 43
Processing (partitura): Schubert_D911-15.xml -> 38_schubert_d911_15

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\directions.py:514: UserWarning: error parsing "Etwas langsam" (UnexpectedCharacters)
  warnings.warn('error parsing "{}" ({})'.format(string, type(e).__name__))
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmusicxml.py:1065: UserWarning: ignoring direction type: metronome {'default-y': '30', 'color': '#000000', 'font-family': 'Plantin MT Std', 'font-style': 'italic', 'font-size': '9.3012', 'font-weight': 'bold'}
  warnings.warn("ignoring direction type: {} {}".format(dt.tag, dt.attrib))

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.000,0.000,0.164,C4,C4,60,Piano - Voice 2,<NA>
1,1,0.000,0.000,0.500,C6,C6,84,Piano - Voice 1,<NA>
2,1,0.164,0.164,0.168,D#4,Eb4,63,Piano - Voice 2,<NA>
3,1,0.332,0.332,0.168,G4,G4,67,Piano - Voice 2,<NA>
4,1,0.500,0.500,0.164,D4,D4,62,Piano - Voice 2,<NA>
5,1,0.500,0.500,0.500,B5,B5,83,Piano - Voice 1,<NA>
6,1,0.664,0.664,0.168,F4,F4,65,Piano - Voice 2,<NA>
7,1,0.832,0.832,0.168,G4,G4,67,Piano - Voice 2,<NA>
8,1,1.000,1.000,0.500,C6,C6,84,Piano - Voice 1,<NA>
9,1,1.000,1.000,0.164,D#4,Eb4,63,Piano - Voice 2,<NA>
10,1,1.164,1.164,0.168,G4,G4,67,Piano - Voice 2,<NA>
11,1,1.332,1.332,0.168,C5,C5,72,Piano - Voice 2,<NA>
12,1,1.500,1.500,0.164,E4,E4,64,Piano - Voice 2,<NA>
13,1,1.500,1.500,0.500,G5,G5,79,Piano - Voice 1,<NA>
14,1,1.664,1.664,0.168,G4,G4,67,Piano - Voice 2,<NA>
15,1,1.832,1.832,0.168,C5,C5,72,Piano - Voice 2,<NA>
16,1,2.000,2.000,0.164,F4,F4,65,Piano - Voice 2,<NA>
17,1,2.000,2.000,0.500,A#5,Bb5,82,Piano - Voice 1,<NA>
18,1,2.164,2.164,0.168,G#4,Ab4,68,Piano - Voice 2,<NA>
19,1,2.332,2.332,0.168,C5,C5,72,Piano - Voice 2,<NA>

Rows: 739, unique pitches: 50
Processing (partitura): Schubert_D911-07.xml -> 39_schubert_d911_07

c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\directions.py:514: UserWarning: error parsing "Langsam." (UnexpectedCharacters)
  warnings.warn('error parsing "{}" ({})'.format(string, type(e).__name__))
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmusicxml.py:1065: UserWarning: ignoring direction type: metronome {'default-y': '30', 'color': '#000000', 'font-family': 'Plantin MT Std', 'font-style': 'italic', 'font-size': '9.3012', 'font-weight': 'bold'}
  warnings.warn("ignoring direction type: {} {}".format(dt.tag, dt.attrib))
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\directions.py:514: UserWarning: error parsing "(sehr leise)" (UnexpectedCharacters)
  warnings.warn('error parsing "{}" ({})'.format(string, type(e).__name__))
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmusicxml.py:1614: UserWarning: Tuplet start and end notes do not belong to the same voice (2 != 1). This might indicate a missing <tuplet type="start"> or <tuplet type="stop">.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmusicxml.py:1614: UserWarning: Tuplet start and end notes do not belong to the same voice (1 != 2). This might indicate a missing <tuplet type="start"> or <tuplet type="stop">.
  warnings.warn(
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmusicxml.py:1065: UserWarning: ignoring direction type: other-direction {'default-y': '13', 'print-object': 'no'}
  warnings.warn("ignoring direction type: {} {}".format(dt.tag, dt.attrib))
c:\Users\egorp\miniconda3\envs\py312latest\Lib\site-packages\partitura\io\importmusicxml.py:1065: UserWarning: ignoring direction type: other-direction {'default-y': '-64', 'print-object': 'no'}
  warnings.warn("ignoring direction type: {} {}".format(dt.tag, dt.attrib))

,Measure,Local Onset,Global Onset,Duration,Pitch,Pitch Enharmonic,MIDI,Voice,xml_id
0,1,0.0,0.0,0.5,E3,E3,52,Piano - Voice 2,<NA>
1,1,0.5,0.5,0.5,B3,B3,59,Piano - Voice 1,<NA>
2,1,0.5,0.5,0.5,E4,E4,64,Piano - Voice 1,<NA>
3,1,0.5,0.5,0.5,G4,G4,67,Piano - Voice 1,<NA>
4,1,1.0,1.0,0.5,D3,D3,50,Piano - Voice 2,<NA>
5,1,1.5,1.5,0.5,B3,B3,59,Piano - Voice 1,<NA>
6,1,1.5,1.5,0.5,E4,E4,64,Piano - Voice 1,<NA>
7,1,1.5,1.5,0.5,G4,G4,67,Piano - Voice 1,<NA>
8,1,2.0,2.0,0.5,C3,C3,48,Piano - Voice 2,<NA>
9,1,2.5,2.5,0.5,C4,C4,60,Piano - Voice 1,<NA>
10,1,2.5,2.5,0.5,E4,E4,64,Piano - Voice 1,<NA>
11,1,2.5,2.5,0.5,G4,G4,67,Piano - Voice 1,<NA>
12,1,3.0,3.0,0.5,G2,G2,43,Piano - Voice 2,<NA>
13,1,3.5,3.5,0.5,B3,B3,59,Piano - Voice 1,<NA>
14,1,3.5,3.5,0.5,E4,E4,64,Piano - Voice 1,<NA>
15,1,3.5,3.5,0.5,G4,G4,67,Piano - Voice 1,<NA>
16,1,4.0,4.0,0.5,A2,A2,45,Piano - Voice 2,<NA>
17,1,4.5,4.5,0.5,E4,E4,64,Piano - Voice 1,<NA>
18,1,4.5,4.5,0.5,F#4,F#4,66,Piano - Voice 1,<NA>
19,1,4.5,4.5,0.5,C4,C4,60,Piano - Voice 1,<NA>

Rows: 1330, unique pitches: 42
Parsed DataFrames:
- 01_sonata29_2: rows=2001, unique_pitches=70, min_duration=0.25, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 02_sonata29_3: rows=5265, unique_pitches=70, min_duration=0.083, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 03_sonata29_4: rows=6525, unique_pitches=71, min_duration=0.062, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 04_sonata32_1: rows=4063, unique_pitches=73, min_duration=0.083, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 05_sonata32_2: rows=6012, unique_pitches=70, min_duration=0.042, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 06_sonata31_1: rows=2712, unique_pitches=69, min_duration=0.125, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 07_sonata31_2: rows=966, unique_pitches=62, min_duration=0.5, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 08_sonata31_3: rows=3843, unique_pitches=70, min_duration=0.062, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 09_sonata14_1: rows=1182, unique_pitches=55, min_duration=0.25, voices=5 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4', 'P0 - Voice 5'])
- 10_sonata14_2: rows=430, unique_pitches=37, min_duration=0.5, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 11_sonata14_3: rows=4924, unique_pitches=60, min_duration=0.125, voices=3 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3'])
- 26_sonata14_1: rows=2170, unique_pitches=59, min_duration=0.125, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 27_sonata14_2: rows=1870, unique_pitches=54, min_duration=0.031, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 28_sonata14_3: rows=2192, unique_pitches=59, min_duration=0.167, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 29_sonata08_1: rows=3231, unique_pitches=55, min_duration=0.125, voices=5 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4', 'P0 - Voice 5'])
- 30_sonata08_2: rows=2086, unique_pitches=56, min_duration=0.062, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 31_sonata08_3: rows=1858, unique_pitches=52, min_duration=0.5, voices=4 (['P0 - Voice 1', 'P0 - Voice 2', 'P0 - Voice 3', 'P0 - Voice 4'])
- 32_mozart_fuge_g_minor: rows=1523, unique_pitches=43, min_duration=0.25, voices=4 (['P1 - Voice 1', 'P2 - Voice 1', 'P3 - Voice 1', 'P4 - Voice 1'])
- 35_special_features: rows=30, unique_pitches=17, min_duration=0.25, voices=3 (['gab4gh9 - Voice 1', 'gab4gh9 - Voice 2', 'qfp3r3j - Voice 1'])
- 36_schubert_d911_08: rows=2048, unique_pitches=41, min_duration=0.25, voices=4 (['Piano - Voice 1', 'Piano - Voice 2', 'Piano - Voice 3', 'Voice - Voice 1'])
- 37_schubert_d911_20: rows=1131, unique_pitches=43, min_duration=0.125, voices=6 (['Piano - Voice 1', 'Piano - Voice 2', 'Piano - Voice 3', 'Piano - Voice 4', 'Piano - Voice 5', 'Voice - Voice 1'])
- 38_schubert_d911_15: rows=739, unique_pitches=50, min_duration=0.125, voices=4 (['Piano - Voice 1', 'Piano - Voice 2', 'Piano - Voice 3', 'Voice - Voice 1'])
- 39_schubert_d911_07: rows=1330, unique_pitches=42, min_duration=0.125, voices=4 (['Piano - Voice 1', 'Piano - Voice 2', 'Voice - Voice 1', 'Voice - Voice 2'])